"""
Part 6 of 39 Authentic Indian Top 10 Posts
Categories: what_happens_if, bureaucracy, banking_problems, credit_cards
"""

PART_6_POSTS = [
    # 5. what_happens_if - Post 3
    {
        "category": "what_happens_if",
        "title": "Top 10 'What Happens If...' Flight Delays, Cancellations & Airport Baggage Claims in India",
        "intro_p1": "Air travel across Indian domestic sectors can be disrupted by fog seasonal delays, technical faults, and baggage mishandling. Knowing passenger rights under DGCA Civil Aviation Requirements (CAR) guarantees meal vouchers, hotel stays, and financial compensation.",
        "intro_p2": "Evaluating airline rights requires referencing DGCA CAR Section 3, Series M provisions, airline customer service commitments, and airport operator rules.",
        "items": [
            ("What happens if your domestic flight is delayed by more than 2 hours?", "Rule: Free Refreshments | Authority: DGCA CAR Section 3 | Option: Meals & Drinks", "Airline must provide free meals and refreshments for delays over 2 hours (Block 1).", "Delay over 6 hours requires airline to offer alternate flight or 100% refund.", "Passengers entitled to full communication facilities at airport.", "Collect refreshment voucher at airline customer service desk near gate."),
            ("What happens if an airline cancels your flight within 24 hours of departure?", "Rule: Alternate Flight or Full Refund + Compensation | Authority: DGCA CAR | Value: Up to ₹10,000", "Airline must offer alternate flight or 100% refund.", "Additionally pay compensation up to ₹10,000 based on flight duration.", "Exempted if cancellation is caused by extraordinary weather/ATC events.", "Demand written reason for cancellation from airline ground staff."),
            ("What happens if an airline denies boarding due to overbooking?", "Rule: Alternate Flight + 200% Compensation | Authority: DGCA CAR | Limit: Up to ₹20,000", "If alternate flight provided within 1 hour: zero compensation.", "If alternate flight beyond 1 hour: airline pays 200% of basic fare + fuel surcharge.", "Passengers choose between monetary refund or alternate transport.", "Never voluntarily give up seat without written compensation voucher."),
            ("What happens if your checked baggage is lost or delayed by domestic airlines?", "Rule: PIR Registration & Daily Expense Allowance | Authority: DGCA & Carriage by Air Act | Compensation: Up to ₹20,000", "File Property Irregularity Report (PIR) before leaving arrival hall.", "Airline pays interim emergency allowance for purchase of essentials.", "Baggage unrecovered after 21 days treated as lost; compensation up to ₹20,000.", "Keep baggage tag receipts stuck to boarding pass safe."),
            ("What happens if your luggage is damaged during transit?", "Rule: Repair or Replacement Claim | Authority: Airline Baggage Policy | Deadline: 7 Days", "Report damaged bag to airline baggage counter before exiting airport.", "File written claim within 7 days of receiving damaged luggage.", "Airline reimburses repair costs or provides replacement suitcase.", "Take clear photo of damaged bag at baggage carousel immediately."),
            ("What happens if you miss your flight due to long airport security queues?", "Rule: Passenger Responsibility | Authority: Airline Conditions of Carriage | Fee: No-Show Fee", "Airlines not legally liable for delays caused by CISF security queues.", "Must pay no-show fee or rebooking difference for next available flight.", "Some airlines offer gate assistance if requested early in check-in hall.", "Arrive 3 hours prior for domestic flights during peak holiday seasons."),
            ("What happens if you leave a personal item (laptop/phone) on the airplane?", "Rule: Lost & Found Retrieval | Authority: Airport Lost & Found / CISF | Verification: Serial No & ID", "Contact airline ground office or airport Lost & Found portal immediately.", "Items handed over to CISF security custody after aircraft search.", "Retrieved upon showing valid government ID and purchase invoice.", "File online Lost & Found query on airport official website."),
            ("What happens if weather conditions force a flight diversion to another city?", "Rule: Duty of Care & Transit | Authority: DGCA Regulations | Duty: Hotel & Food", "Airline must provide ground transportation or hotel accommodation at diverted airport.", "Flights resume once destination weather permits.", "Passengers can disembark at diverted airport if customs/security allows.", "Follow airline ground staff instructions for hotel transfers."),
            ("What happens if you need to cancel a flight ticket within 24 hours of booking?", "Rule: Zero Cancellation Fee Window | Authority: DGCA CAR 24-Hour Rule | Condition: Flight 7 Days Away", "Can cancel or amend ticket within 24 hours of booking without any penalty.", "Applies if booking was made at least 7 days prior to flight departure.", "Full refund processed back to original payment method.", "Book directly on airline website for seamless 24-hour zero-fee cancellation."),
            ("What happens if medical emergency prevents you from traveling on booked date?", "Rule: Credit Shell / Date Change Fee Waiver | Authority: Airline Compassionate Policy | Requirement: Medical Certificate", "Submit certified medical certificate from registered doctor to airline customer care.", "Airlines grant fee-waiver date change or issue credit shell valid for 1 year.", "Policy varies by carrier; low-cost airlines require advance notification.", "Email medical documents to airline customer support before flight departure.")
        ]
    },

    # 6. bureaucracy - Post 1
    {
        "category": "bureaucracy",
        "title": "Top 10 Complex Indian Bureaucratic Processes Explained Simply: Aadhaar, PAN & Passport",
        "intro_p1": "Navigating Indian administrative procedures can feel overwhelming due to overlapping government portals, documentation requirements, and gazette notifications. Demystifying these processes guarantees hassle-free approval.",
        "intro_p2": "Evaluating government documentation requires referencing UIDAI circulars, NSDL/UTIITSL guidelines, Passport Seva manuals, and Gazetted officer verification protocols.",
        "items": [
            ("How to update address on Aadhaar Card online without document proof?", "Portal: UIDAI MyAadhaar | Method: Head of Family (HoF) Consent | Fee: ₹50", "Log into MyAadhaar portal and select 'Address Update via Head of Family'.", "Enter HoF's Aadhaar number; HoF receives OTP for verification.", "HoF approves request on portal within 30 days.", "Requires HoF to have updated address on their Aadhaar already."),
            ("How to link PAN card with Aadhaar after passing penalty deadline?", "Portal: Income Tax e-Filing | Penalty: ₹1,000 under Sec 234H | TAT: 4-7 Days", "Pay ₹1,000 fee under Minor Head 500 on e-Filing portal.", "Submit PAN-Aadhaar link request 24 hours after tax fee payment.", "Unlinked PANs become inoperative, stopping bank interest and IT refunds.", "Ensure name spelling matches character-for-character across both cards."),
            ("How to change name on government documents after marriage or legal name change?", "Authority: Dept of Publication | Process: Central Gazette Notification | Cost: ₹1,100-1,500", "Execute sworn affidavit before First Class Judicial Magistrate.", "Publish name change advertisement in 2 daily newspapers (1 local, 1 English).", "Submit dossier to Department of Publication for Gazette printing.", "Gazette copy serves as master proof for changing PAN, Aadhaar, and Passport."),
            ("How to issue a Duplicate Driving License if original is lost?", "Portal: Parivahan Sarathi | Requirement: LLD Form & Police LOR | Fee: ₹400-600", "File online Lost Report (LOR) on state police portal.", "Apply for duplicate DL on Parivahan Sarathi portal using DL number.", "Upload police report, affidavit, and pay fee online.", "Physical DL dispatched to registered address via Speed Post."),
            ("How to transfer vehicle ownership (RTO Form 29 & 30) after buying second-hand car?", "Portal: Vahan Citizen Services | Forms: Form 29 (Notice) & Form 30 (Application) | TAT: 30 Days", "Submit seller and buyer signed Form 29 and Form 30 to regional RTO.", "Attach original RC, valid insurance, PUC certificate, and buyer address proof.", "Clear all pending traffic e-challans before submitting file.", "Complete biometric buyer verification if required by state RTO."),
            ("How to obtain non-creamy layer OBC certificate for government jobs/education?", "Portal: State Revenue Portal / E-District | Limit: Annual Income under ₹8 Lakhs | Validity: 1 Financial Year", "Obtain income certificate from Tehsildar proving annual family income under ₹8L.", "Submit caste validity proof of father/paternal relatives.", "Non-creamy layer status excludes salary and agricultural income.", "Apply 2 months before job/admission application deadlines."),
            ("How to register a Marriage Certificate online in Indian metros?", "Portal: State E-District / Sub-Registrar | Law: Hindu Marriage Act / Special Marriage Act | TAT: 15-30 Days", "Apply online on state portal and upload couple photo, age proof, and wedding card.", "Book appointment at Sub-Registrar office with 3 adult witnesses.", "Sub-Registrar issues digital certified Marriage Certificate.", "Special Marriage Act requires mandatory 30-day public notice period."),
            ("How to correct Date of Birth on Birth Certificate years after registration?", "Authority: Municipal Corp Registrar of Births | Order: Magistrate Order / School TC | TAT: 30-60 Days", "Submit application to Municipal Health Officer with SSLC marksheet/school TC.", "If delay exceeds 1 year, requires First Class Magistrate order.", "Registrar updates master birth ledger and issues corrected certificate.", "School leaving certificate acts as primary supporting evidence."),
            ("How to issue a Police Clearance Certificate (PCC) for foreign visa/job?", "Portal: Passport Seva Kendra (PSK) | Fee: ₹500 | TAT: 7-14 Days", "Apply online on Passport Seva portal under PCC section.", "Attend appointment at PSK for biometric verification and document check.", "Local police station conducts physical residence verification.", "PCC dispatched via post once police verification report clears."),
            ("How to digitize old physical land records (7/12 Extract / Khata) online?", "Portal: State Bhulekh / AnyRoR Portal | Service: Digital Record Search | Fee: Nominal", "Access state land record portal (e.g. Mahabhulekh, Banglarbhumi, Bhoomi).", "Search by survey number, district, and owner name.", "Download digitally signed land record copy valid for bank loans.", "Visit Talathi/Village Revenue Officer if survey number records are unlinked.")
        ]
    },

    # 6. bureaucracy - Post 2
    {
        "category": "bureaucracy",
        "title": "Top 10 Land Registry, Khata & Property Mutation Procedures Demystified",
        "intro_p1": "Purchasing real estate in India involves complex property title verification, stamp duty calculations, and municipal property tax mutation. Understanding legal paperwork protects buyers against property fraud.",
        "intro_p2": "Evaluating property paperwork requires referencing Registration Act 1908, Transfer of Property Act 1882, municipal corporation bylaws, and RERA regulations.",
        "items": [
            ("What is Property Mutation (Khata Transfer) and why is it distinct from Registration?", "Purpose: Municipal Tax Records | Authority: Revenue Dept / Municipal Corp | Protection: Prevents Title Fraud", "Registration transfers ownership; Mutation updates municipal tax register.", "Without mutation, property tax bills continue issuing in seller's name.", "Essential for obtaining electricity connections and selling property later.", "Apply for mutation within 60 days of sale deed registration."),
            ("How to verify Encumbrance Certificate (EC) before buying property?", "Period: 13 to 30 Years | Authority: Sub-Registrar Office (SRO) | Sign: Nil Encumbrance", "EC reflects all registered sales, mortgages, and legal claims on property.", "Obtain Form 15 (Encumbrances exist) or Form 16 (Nil Encumbrance).", "Ensures property is free from bank liens or legal disputes.", "Verify EC records online via state registration portal."),
            ("How to convert Agricultural Land to Non-Agricultural (NA) use?", "Process: Land Use Conversion | Authority: District Collector / Revenue Dept | Fee: NA Premium", "Agricultural land cannot be used for residential/commercial construction without NA order.", "Apply to District Collector with land survey map and title chain.", "Pay NA conversion premium and development charges.", "Verify NA order layout approval by town planning department."),
            ("What is a Occupancy Certificate (OC) and can you legally live without it?", "Status: Mandatory for Living | Authority: Municipal Corp / Development Authority | Risk: Disconnection", "OC certifies building constructed according to approved Sanction Plan.", "Living in building without OC is legally unauthorized; risks utility cut-off.", "Banks refuse home loans for flats lacking valid OC.", "Insist on builder producing OC before taking flat possession."),
            ("How to check if real estate project is RERA Registered?", "Portal: State RERA Web Portal | Mandatory: Projects over 500 sq m or 8 flats | Verification: RERA Reg No", "Search project RERA registration number on state RERA website.", "Check sanctioned floor plans, promoter background, and completion timeline.", "RERA forces builders to park 70% funds in dedicated escrow account.", "Never pay advance money for non-RERA registered projects."),
            ("How to calculate Stamp Duty and Registration Fees accurately?", "Value: Circle Rate vs Sale Value (Whichever is Higher) | Rate: 4%-8% Stamp + 1% Reg | Discount: Female Buyers", "Stamp duty calculated on higher of circle rate (guideline value) or agreement value.", "Many states offer 1-2% stamp duty discount for female buyers.", "Pay stamp duty via e-Stamping portal or franking banks.", "Calculate circle rate using official municipal portal calculator."),
            ("How to resolve Khata A vs Khata B property classification in Bangalore?", "Status: Municipal Classification | Authority: BBMP | Limitation: Bank Loan Restrictions", "A Khata properties are fully legal with approved plans and OC.", "B Khata properties have building violations or unreleased layouts.", "B Khata flats face bank loan difficulties and resale challenges.", "Convert B Khata to A Khata by paying betterment charges if eligible."),
            ("How to execute a Gift Deed for property transfer between family members?", "Stamp Duty: Concessional Rate | Registration: Mandatory at SRO | Tax: Tax-Free under Sec 56", "Transferring property via Gift Deed requires registration at Sub-Registrar office.", "Concessional stamp duty applies for transfers to immediate relatives in many states.", "Gift Deed is irrevocable once accepted by donee.", "Ensure donee signs Gift Deed accepting transfer during registration."),
            ("How to remove Bank Lien (Home Loan NOC) from property records after loan closure?", "Document: Deed of Reconveyance / NOC | Authority: SRO & CERSAI | Action: Lien Removal", "Obtain original property documents, NOC, and No Due Certificate from bank.", "Register Deed of Reconveyance at Sub-Registrar office where loan was marked.", "Ensure bank updates CERSAI registry database clearing mortgage record.", "Collect original sale deed title chain from bank safe vault."),
            ("How to handle power of attorney (POA) property sales safely?", "Risk: High Fraud Vulnerability | Authority: Supreme Court Ruling | Rule: Registration Mandatory", "Supreme Court ruled POA sales do not confer legal ownership title.", "General Power of Attorney (GPA) must be registered at SRO to be valid.", "Verify POA grantor is alive and POA has not been revoked.", "Always insist on direct sale deed execution by property owner.")
        ]
    }
]
