"""
Part 10 of 39 Authentic Indian Top 10 Posts
Categories: credit_cards, tax_edge_cases, error_dictionary
"""

PART_10_POSTS = [
    # 8. credit_cards - Post 3
    {
        "category": "credit_cards",
        "title": "Top 10 Zero Forex Fee Credit Cards & International Travel Spending Playbooks",
        "intro_p1": "Traveling abroad from India with traditional credit cards incurs high 3.5% foreign exchange markup fees plus GST. Zero forex markup credit cards eliminate international markup fees completely.",
        "intro_p2": "Selecting zero forex cards involves comparing markup fees, ATM withdrawal charges, TCS tax implications, and lounge access benefits worldwide.",
        "items": [
            ("Ixigo AU Credit Card - Zero Forex & Airport Lounge Perks", "Forex Fee: 0% | Annual Fee: Lifetime Free | Lounge: 16 Domestic + 1 Intl", "Offers 0% foreign currency markup on all international transactions.", "Includes complimentary Railway and Airport lounge access.", "Earn 20 reward points per ₹200 spent on Ixigo flight bookings.", "Ideal everyday travel card for zero forex expenditure."),
            ("IDFC FIRST Wow Credit Card - Secured Zero Forex Card", "Forex Fee: 0% | Annual Fee: Lifetime Free | Qualification: Fixed Deposit (FD) Based", "FD-backed card requiring zero credit history or income proof.", "0% forex markup fee worldwide across online and offline merchants.", "Earn 4x reward points on all international spends.", "Instant digital issuance against a ₹10,000 fixed deposit."),
            ("Niyo Global Debit & Credit Card (SBM / DCB Bank)", "Forex Fee: 0% | Annual Fee: Zero | App: Real-Time Currency Converter", "Popular zero forex card linking real-time app currency converter.", "Zero markup fee on live interbank exchange rates.", "Includes free international ATM withdrawal features (bank fees apply).", "Load INR in app and auto-convert seamlessly during international POS swipes."),
            ("Scapia Federal Credit Card - Travel Rewards & Zero Forex", "Forex Fee: 0% | Annual Fee: Lifetime Free | Lounge: Unlimited (Milestone Based)", "0% markup fee on all international foreign currency purchases.", "Earn 20% Scapia coins on flight and hotel bookings in Scapia app.", "Unlimited domestic airport lounge access upon reaching ₹5,000 monthly spend.", "100% digital onboarding via mobile app in 5 minutes."),
            ("RBL World Safari Credit Card - Travel Insurance & Zero Forex", "Forex Fee: 0% | Annual Fee: ₹3,000 | Bonus: MakeMyTrip Voucher", "Dedicated travel card with 0% markup fee on foreign currency transactions.", "Includes comprehensive travel insurance cover for lost baggage and passport.", "Earn 5 travel points per ₹100 spent on international travel.", "Complimentary lounge access at international airports."),
            ("Club Vistara IDFC FIRST Credit Card - Zero Forex Upgrade Option", "Forex Fee: 0% (Select Tiers) | Annual Fee: ₹4,999 | Benefit: Free Premium Economy Tickets", "Combines Vistara flight ticket milestones with low/zero forex fee benefits.", "Includes complimentary airport lounge access worldwide.", "Accelerated point earnings on foreign currency spends.", "Redeem points for international flight seat upgrades."),
            ("Fi Federal Credit Card - Smart Zero Forex Card", "Forex Fee: 0% (Pro Tiers) | Annual Fee: Zero | Feature: Automated Savings", "Offers 0% forex markup for Fi Money account holders in Pro/Infinite tiers.", "Real-time spend analytics and reward tracking in Fi app.", "Earn 4x rewards on top spending categories abroad.", "Keep Fi account balance maintained to retain zero forex status."),
            ("BookMyShow RBL Play Credit Card - International Entertainment Perks", "Forex Fee: Reduced 1.5% | Annual Fee: ₹500 | Feature: Free Movie Tickets", "Low forex fee structure combined with entertainment discount benefits.", "Ideal for travelers attending international concerts and shows.", "Earn reward points on foreign currency ticket bookings.", "Waive annual fee on reaching ₹1.5 Lakhs annual spend."),
            ("Understanding TCS (Tax Collected at Source) on International Credit Card Spends", "Rule: LRS Ceiling | Threshold: ₹7 Lakhs | TCS Rate: 20% Above Threshold", "International credit card spends are exempt from LRS TCS up to ₹7 Lakhs per year.", "Spends exceeding ₹7 Lakhs attract 20% TCS (5% for education/medical).", "TCS is NOT a tax cost; claim 100% refund while filing annual income tax return.", "Track cumulative annual foreign spends to manage TCS cash flow."),
            ("International ATM Cash Withdrawal Playbook for Indian Cards", "Fee Structure: Flat ₹250-500 + ATM Operator Fee | Advice: Minimize Cash Withdrawals", "Withdrawing cash abroad incurs flat bank ATM fees plus local ATM operator charges.", "Always select 'Debit in Local Currency' (NOT INR) at overseas ATMs to avoid DCC markup.", "Dynamic Currency Conversion (DCC) charges hidden 5-8% extra conversion fee.", "Carry a mix of zero forex cards and minimal local cash currency.")
        ]
    },

    # 9. tax_edge_cases - Post 1
    {
        "category": "tax_edge_cases",
        "title": "Top 10 Capital Gains Tax Edge Cases for Stocks, Mutual Funds & Crypto in India",
        "intro_p1": "Indian capital gains tax rules under Section 112A and 115BBH impose specific tax rates on equity mutual funds, debt funds, real estate, and Virtual Digital Assets (crypto).",
        "intro_p2": "Navigating tax edge cases requires understanding grandfathering clauses, indexation benefits, loss set-off rules, and Advance Tax payment schedules.",
        "items": [
            ("Equity LTCG Exemption Threshold & Section 112A Mechanics", "Tax Rate: 12.5% | Exemption: ₹1.25 Lakhs / yr | Period: 12 Months", "Long-Term Capital Gains (LTCG) on listed equities & equity MFs tax-free up to ₹1.25 Lakhs per financial year.", "Gains exceeding ₹1.25 Lakhs taxed at flat 12.5% without indexation.", "Harvest ₹1.25 Lakhs capital gains annually to rebalance portfolio tax-free.", "Ensure STT (Securities Transaction Tax) was paid on acquisition and sale."),
            ("Taxation of Debt Mutual Funds Post-2023 Amendment", "Tax Rate: Slabs Rate (As per Income) | Indexation: Removed | Holding: Any Period", "Debt MFs acquired after April 1, 2023 lost indexation benefits completely.", "All gains from debt funds classified as Short-Term Capital Gains (STCG) regardless of holding period.", "Taxed at individual slab rates (up to 30% + surcharge).", "Use Arbitrage Funds (taxed as equity) for low-risk short-term parking."),
            ("Set-off and Carry Forward Rules for Capital Losses", "LTCG Loss: Set off against LTCG only | STCG Loss: Set off against STCG & LTCG | Carry Forward: 8 Years", "Short-Term Capital Loss (STCL) can be set off against both STCG and LTCG.", "Long-Term Capital Loss (LTCL) can ONLY be set off against LTCG.", "Unadjusted losses carried forward up to 8 assessment years.", "File ITR on or before original due date (July 31) to carry forward losses."),
            ("Taxation of Virtual Digital Assets (Crypto & NFTs) under Section 115BBH", "Tax Rate: Flat 30% + Surcharge | TDS: 1% under Sec 194S | Loss Set-off: Strictly Prohibited", "Gains on crypto and NFTs taxed at flat 30% without basic exemption limit benefit.", "Zero deduction allowed except cost of acquisition.", "Loss in one crypto pair CANNOT be set off against gain in another crypto pair.", "1% TDS deducted on all crypto sell transactions on Indian exchanges."),
            ("Taxation of Sovereign Gold Bonds (SGB) on Maturity vs Secondary Sale", "Maturity Tax: 100% Tax-Free | Secondary Sale Tax: 12.5% LTCG | Period: 3 Years", "Capital gains on SGBs redeemed with RBI upon 8-year maturity are COMPLETELY TAX-FREE.", "Premature secondary market sales on stock exchange before 8 years attract capital gains tax.", "Holding SGBs over 3 years qualifies as LTCG taxed at 12.5%.", "Hold SGBs till official RBI maturity for 100% tax exemption."),
            ("REITs and InvITs Distribution Taxation Mechanics", "Components: Dividend, Interest, Repayment of Debt | Tax Treatment: Split Matrix", "REIT payouts split into Dividend, Interest, Rental Income, and Repayment of Debt.", "Dividend tax-free if SPV opted for old tax regime; Interest taxed at slab rate.", "Repayment of debt portion taxed as capital gains if exceeds cost of acquisition.", "Check annual tax statement issued by REIT manager before filing ITR."),
            ("Taxation of Employee Stock Options (ESOPs) & RSUs for Tech Workers", "Prerequisite Tax: Exercise Date (Slab Rate) | Capital Gain Tax: Sale Date (STCG/LTCG)", "ESOPs taxed at TWO stages: First as Perquisite (salary slab) on exercise date.", "Second as Capital Gains on final sale date based on FMV on exercise date.", "DIPP-recognized startups eligible for deferred ESOP tax payment.", "Keep Form 16 and ESOP exercise statement synchronized."),
            ("Taxation of US Stocks & Foreign Equities for Indian Residents", "LTCG Period: 24 Months | LTCG Rate: 12.5% | Schedule FA: Mandatory Disclosure", "Foreign equities (e.g. US stocks) qualify as LTCG after 24 months holding.", "LTCG taxed at 12.5% without indexation; STCG taxed at individual slab rates.", "Must declare all foreign stock holdings in Schedule FA of ITR.", "Claim Foreign Tax Credit (FTC) by filing Form 67 for US dividend withholding tax."),
            ("Capital Gains Tax Exemption via Section 54F (Property Reinvestment)", "Condition: Reinvest Net Sale Consideration | Timeline: 1 yr prior / 2 yrs post sale | Asset: Residential House", "Exempt LTCG from sale of shares/land by investing net sale proceeds in residential house.", "Must buy house within 1 year before or 2 years after asset sale date.", "Capped at maximum reinvestment limit of ₹10 Crores.", "Deposit unutilized proceeds in Capital Gains Account Scheme (CGAS) before ITR deadline."),
            ("Advance Tax Schedule & Interest Penalties under Section 234B & 234C", "Threshold: Tax Liability > ₹10,000 | Installments: June (15%), Sept (45%), Dec (75%), March (100%)", "If net tax liability exceeds ₹10,000, must pay Advance Tax in 4 quarterly installments.", "Failure triggers 1% per month interest penalty under Section 234B and 234C.", "Capital gains occurring after an installment date can be paid in remaining quarters.", "Pay estimated advance tax immediately in quarter capital gain is realized.")
        ]
    }
]
