"""
Part 15 of 39 Authentic Indian Top 10 Posts
Categories: moving_to_india, can_i_carry
"""

PART_15_POSTS = [
    # 12. moving_to_india - Post 1
    {
        "category": "moving_to_india",
        "title": "Top 10 Relocation Logistics Steps when Moving to India from USA/UK/Europe",
        "intro_p1": "Relocating to India as a returning NRI or expat involves container shipping logistics, customs duty clearance, foreign bank account conversions, and tax residence planning.",
        "intro_p2": "Managing international relocation requires executing Transfer of Residence (TR) rules, shipping personal effects duty-free, and updating NRI banking status.",
        "items": [
            ("Executing Transfer of Residence (TR) Rules for Duty-Free Baggage Clearance", "Rule: Customs Baggage Rules Rule 6 | Requirement: 2 Years Overseas Stay | Benefit: Duty-Free Personal Effects", "Returning NRIs living abroad for 2+ years can ship household goods duty-free.", "Covers used furniture, books, clothing, and personal appliances.", "Customs allows container arrival within 1 month before or 2 months after NRI arrival.", "Submit copy of passport with foreign entry/exit stamps to customs broker."),
            ("Shipping Household Goods & Container Cargo Logistics (FCL vs LCL)", "Container: 20ft / 40ft FCL | LCL: Shared Shipping | Timeline: 45-60 Days Transit", "Choose Full Container Load (FCL) for full home relocation; LCL for smaller loads.", "Book international movers offering door-to-door customs clearance.", "Ensure detailed inventory list with serial numbers is prepared for customs.", "Take comprehensive marine cargo transit insurance covering door-to-door damage."),
            ("Converting Overseas Driving License to Indian Driving License", "Authority: Regional RTO | Process: Exemption from Driving Test (Select Countries) | Requirement: DL Verification", "Some state RTOs issue Indian DL based on valid foreign license without driving test.", "Requires notarized copy of foreign DL, embassy verification, and medical Form 1A.", "Must pass basic online RTO traffic sign computer test.", "Apply on Parivahan portal under 'Direct DL for Foreign License Holder'."),
            ("Redesignating Resident Bank Accounts to NRE/NRO Accounts", "Mandate: FEMA Regulations | Timeline: Within 3 Months of Return | Action: Bank Status Update", "Notify Indian banks within 3 months of returning permanently to India.", "Re-designate existing resident savings accounts to NRO accounts.", "NRE accounts can be retained or converted to RFC (Resident Foreign Currency) accounts.", "RFC accounts allow holding foreign currency (USD/GBP/EUR) tax-free in India."),
            ("Customs Duty Rules on Bringing Used Electronics & Appliances", "Concession: Concessional Duty Tiers | Exemption: 1 Laptop Duty-Free | Appliance Cap: ₹5 Lakhs", "One used laptop per passenger imported duty-free regardless of age.", "Used television sets attract flat 38.5% customs duty without basic exemption.", "Used home appliances (fridge, washing machine) imported under TR concessional duty slabs.", "Declare all electronics in Customs Baggage Declaration form upon arrival."),
            ("Planning Foreign Asset Disclosures & RNOR Tax Status", "Status: Resident but Not Ordinarily Resident | Duration: 2 to 3 Financial Years | Benefit: Foreign Income Tax-Free", "Returning NRIs enjoy RNOR tax status for 2-3 years after returning.", "Global foreign income remains tax-free in India during RNOR period.", "Liquidate foreign stocks and offshore assets tax-free while in RNOR status.", "Consult Indian cross-border CA before transferring overseas investment portfolios."),
            ("Shipping Pets (Dogs/Cats) to India under Directorate General of Foreign Trade (DGFT)", "Permit: DGFT Import License | Requirement: No Objection Certificate (AQCS) | Cap: 2 Pets per Passenger", "Importing pets requires DGFT import license and AQCS NOC 7 days prior to travel.", "Pets must have valid rabies vaccination and microchip ID.", "Mandatory 14-day home quarantine required upon arrival in India.", "Engage certified pet relocation agency to handle airline and AQCS paperwork."),
            ("Setting Up Local Mobile Connectivity & e-SIM Activation", "Provider: Jio / Airtel 5G | Requirement: Passport + OCI/Visa + Local Reference | Activation: 2 Hours", "Foreign passport holders and OCI cardholders can get prepaid/postpaid Indian SIM.", "Requires physical passport verification and local reference contact details at store.", "e-SIM activation takes 2 hours after QR code scanning.", "Select postpaid plan for uninterrupted banking OTP delivery."),
            ("Opening Resident Demat & Trading Accounts for Stock Portfolio Transfers", "Process: NRI to Resident Demat Conversion | Authority: SEBI / NSDL / CDSL | Action: Broker Intimation", "Convert NRI PIS/Non-PIS Demat accounts to resident Demat accounts.", "Transfer Indian equity shares from NRE/NRO Demat to resident Demat account.", "Update KYC details with depository participant (broker).", "Prevents trading account freeze due to residency status mismatch."),
            ("School Admission Logistics for Children (IB / IGCSE vs CBSE)", "Curricula: International Baccalaureate / Cambridge IGCSE | Process: Document Attestation | Window: Jan - April", "Admit children returning from abroad into IB or Cambridge IGCSE accredited schools.", "Requires attested school transcripts and transfer certificate from foreign school.", "Foreign school documents must be apostilled or endorsed by Indian Embassy.", "Apply for school admissions 6 months prior to academic year start.")
        ]
    },

    # 12. moving_to_india - Post 2
    {
        "category": "moving_to_india",
        "title": "Top 10 Housing Search, Tenant Agreement & Deposit Negotiation Hacks in Indian Metros",
        "intro_p1": "Renting residential property in Indian metros like Bengaluru, Mumbai, and Gurgaon involves negotiating high security deposits, broker fees, and maintenance terms.",
        "intro_p2": "Securing rental property requires understanding registered leave and license agreements, lock-in period clauses, deposit refund terms, and RWA guidelines.",
        "items": [
            ("Negotiating Rental Security Deposits in Bengaluru vs Mumbai vs Gurgaon", "Deposit Standard: Bengaluru (5-10 Months) | Mumbai (3-6 Months) | Gurgaon (2 Months)", "Bengaluru landlords traditionally demand 6-10 months rent as security deposit; negotiate down to 3-4 months.", "Gurgaon and Delhi NCR standard deposit is 2 months rent.", "Include explicit deposit refund timeline (max 30 days) in agreement.", "Deduct final month rent from deposit if landlord resists returning cash."),
            ("Drafting & Registering Leave and License Agreements", "Framework: Registration Act | Mandate: Mandatory Registration in Maharashtra | Cost: 0.25% Stamp Duty", "Always execute formal Leave and License Agreement registered at Sub-Registrar office.", "Notarized agreements carry low legal weight compared to registered agreements.", "Registration mandatory in Maharashtra; highly recommended in all states.", "Ensures legal tenant protection against arbitrary eviction."),
            ("Navigating Lock-In Periods & Early Termination Notice Clauses", "Standard Lock-in: 6 to 11 Months | Notice Period: 1 to 2 Months | Penalty: Forfeiture of Deposit", "Lock-in clause legally binds tenant and landlord to minimum stay period.", "Terminating lease during lock-in period obligates paying rent for remaining lock-in months.", "Ensure agreement includes diplomatic / job transfer exit exception clause.", "Standard notice period after lock-in is 1 to 2 months."),
            ("Understanding Maintenance Charges & Municipal Property Tax Liabilities", "Rule: Landlord pays Property Tax | Maintenance: Fixed vs Per Sq Ft | BBPS Payment", "Landlord is legally responsible for paying annual municipal property tax.", "Tenant pays monthly society maintenance fee unless agreement specifies 'inclusive'.", "Verify if society maintenance includes GST (applies if maintenance > ₹7,500/mo).", "Clarify who pays major structural repair costs versus minor maintenance."),
            ("Verifying Landlord Title Ownership & Encumbrance before Paying Advance", "Document: Sale Deed / Khata / Property Tax Receipt | Check: Title Verification | Risk: Sub-let Fraud", "Inspect landlord's original sale deed and latest property tax receipt.", "Prevents paying security deposit to sub-tenants or unauthorized brokers.", "Ensure bank account for rent transfer matches title deed owner name.", "Never pay token advance without verifying owner identity proof."),
            ("RWA (Resident Welfare Association) Tenant Onboarding & Move-In Fees", "RWA Charges: Move-in / Move-out Fee | Rule: Capped by High Court Rulings | Move-In Pass", "Housing societies levy move-in/move-out fees for elevator and common area use.", "RWA cannot charge exorbitant discriminatory fees to tenants versus owners.", "Obtain tenant move-in NOC pass from RWA manager prior to shift date.", "Check society rules regarding pet ownership and visitor parking."),
            ("Negotiating Brokerage Fees & Direct Owner Portals (NoBroker / MagicBricks)", "Standard Brokerage: 1 Month Rent | Direct Portals: NoBroker / Housing | Savings: Full Month Rent", "Standard broker commission is 1 month rent; negotiate down to 15 days for multi-year leases.", "Use direct owner portals (NoBroker, MagicBricks Premium) to eliminate brokers.", "Ensure broker provides written receipt specifying scope of service.", "Broker fee payable ONLY after registered agreement execution and key handover."),
            ("Painting & Wear-and-Tear Deposit Deduction Clauses", "Standard Deduction: 1 Month Rent for Painting | Rule: Fair Wear & Tear Excluded | Inspection", "Landlords often deduct 1 month rent for painting upon move-out.", "Specify in agreement that painting deduction applies ONLY if stay is under 2 years.", "Fair wear and tear (faded wall paint, minor floor scratches) cannot be penalized.", "Take full video walkthrough of flat on move-in day to document existing defects."),
            ("Commercial Utility Tariff Conversion & Power Backup Metering", "Tariff: Residential vs Commercial | Sub-Meter: DG Backup Charges | Rate: ₹15-25 / Unit", "Ensure electricity connection is on residential tariff (not commercial).", "DG power backup electricity in gated societies is metered separately at higher rates (₹15-25/unit).", "Clear all pending electricity and piped gas bills of previous tenant before moving in.", "Note initial electricity meter reading on agreement commencement date."),
            ("Obtaining Landlord NOC & Property Tax Receipt for HRA Tax Exemption", "Requirement: Landlord PAN (if rent > ₹1 Lakh/yr) | Form: Form 12BB | Benefit: HRA Tax Deduction", "Employers require landlord's PAN card to grant HRA tax exemption for rent > ₹1L/year.", "If landlord has no PAN, obtain signed Form 60 declaration from landlord.", "Ensure rental agreement lists full employee name as primary tenant.", "Pay rent via bank transfer / UPI to maintain digital audit trail for IT return.")
        ]
    },

    # 12. moving_to_india - Post 3
    {
        "category": "moving_to_india",
        "title": "Top 10 International Schooling & Expat Healthcare Integration Logistics in India",
        "intro_p1": "Expat and returning families moving to India require smooth school admission transitions (IB/IGCSE curricula) and comprehensive private health insurance coverage.",
        "intro_p2": "Integrating family logistics requires evaluating international school accreditation, corporate health insurance top-ups, and cashless hospital networks.",
        "items": [
            ("Selecting International Schools: IB World Schools vs Cambridge IGCSE in Indian Metros", "Curricula: IB PYP/MYP/DP vs IGCSE A-Levels | Accreditation: IB / CAIE | Metros: Blr, Mum, NCR", "IB (International Baccalaureate) offers holistic inquiry-based learning suitable for global moves.", "Cambridge IGCSE provides structured exam-oriented curriculum widely recognized in UK/India.", "Major hubs: Bengaluru (TISB, Indus), Mumbai (DAIS, Oberoi), Gurgaon (Heritage, Pathways).", "Apply 6-9 months in advance as international school seats fill fast."),
            ("School Admission Eligibility, Document Attestation & Equivalency Certificates", "Authority: Association of Indian Universities (AIU) | Document: School Transcript | Attestation: Embassy", "Transferring children from foreign schools requires transcripts attested by Indian Embassy.", "AIU issues Grade 10/12 equivalency certificates for overseas school boards.", "Verify school's affiliation on official IB (ibo.org) or Cambridge portal.", "Obtain detailed syllabus breakdown from foreign school to assist grade placement."),
            ("School Transportation, Bus Logistics & Safety Standards", "Safety: GPS Tracking & CCTV | Transport: AC School Buses | Supervision: Bus Nanny", "Top international schools operate fleet AC buses with GPS tracking and speed governors.", "Verify bus route coverage before finalizing residential housing location.", "Commute times in metros like Mumbai and Bengaluru can exceed 60 minutes.", "Select housing within 5-8 km radius of chosen school campus."),
            ("Navigating Expat Private Health Insurance & Local Cashless Hospital Networks", "Coverage: Private Health Insurance + Top-up | Hospital Networks: Apollo, Fortis, Max, Manipal | Claim: Cashless TPA", "Secure comprehensive private health insurance covering top private hospital chains.", "Ensure policy includes cashless hospitalization via Third Party Administrator (TPA).", "Top chains: Manipal (Bengaluru), Max/Fortis (NCR), Apollo/Hinduja (Mumbai/Chennai).", "Maintain physical health card and TPA authorization code in emergency wallet."),
            ("Corporate Group Health Insurance (GHI) Top-Ups & Super Top-Up Plans", "Base Cover: Corporate ₹5 Lakhs | Super Top-Up: ₹20-50 Lakhs | Deductible: Base Policy", "Corporate health insurance (₹5-10L) is often inadequate for major medical procedures.", "Purchase individual Super Top-Up health plan to increase total coverage to ₹50 Lakhs.", "Super top-up triggers once base corporate policy threshold is exhausted.", "Requires zero medical check-up if bought below age 45."),
            ("Vaccination Schedules & Pediatric Healthcare Integration", "Framework: Indian Academy of Pediatrics (IAP) vs CDC/NHS | Action: Pediatrician Alignment", "Align child's vaccination record with Indian Academy of Pediatrics (IAP) schedule.", "Additional vaccines recommended in India: Typhoid, Hepatitis A, Japanese Encephalitis.", "Consult international-grade pediatric clinics (e.g. Cloudnine, Rainbow Children's).", "Carry foreign vaccination record book to local pediatrician."),
            ("Dental, Optical & Wellness Outpatient (OPD) Coverage Hacks", "Coverage: OPD Rider / Corporate Wellness Allowance | Discount: Dental Chains", "Standard Indian health insurance policies exclude outpatient OPD and dental care.", "Add OPD coverage rider or utilize corporate wellness reimbursement allowances.", "Major dental chains (Clove Dental, Sabka Dentist) offer annual subscription plans.", "Pay OPD consultation fees via health wallet for tax benefits under 80D."),
            ("Emergency Medical Response & Ambulance Logistics (108 vs Private)", "Emergency No: 108 (Govt) / Private Hospital Helplines | Service: Cardiac AC Ambulance", "Government 108 emergency service offers free ambulance response nationwide.", "Private hospital chains run dedicated ACLS (Advanced Cardiac Life Support) ambulances.", "Save direct emergency numbers of nearest 24/7 private hospital on phone speed dial.", "Keep emergency cash and identity documents ready in house entrance drawer."),
            ("Expat Prescription Medication Continuity & Importing Personal Drugs", "Regulation: CDSCO Rules | Exemption: Personal Medical Import (Form 12B) | Limit: 100 Doses", "Importing personal prescription medicines requires doctor prescription and Form 12B.", "Ensure foreign medications have exact generic chemical equivalents available in India.", "Indian pharmacy chains (Apollo Pharmacy, 1mg, Netmeds) offer online delivery.", "Carry 3-month supply of specialized prescription drugs when relocating."),
            ("Mental Health & Expat Relocation Counseling Services", "Support: Relocation Stress / Cross-Cultural Adaptation | Platforms: Mindhouse, MPower, Amaha", "Relocation stress and cultural transition challenges affect expat families.", "Access online therapy and counseling platforms specializing in expat integration.", "International schools employ full-time child psychologists and guidance counselors.", "Join local expat social groups (e.g. Bangalore Expat Club, Gurgaon Expat Network).")
        ]
    }
]
