"""
Part 8 of 39 Authentic Indian Top 10 Posts
Categories: banking_problems, credit_cards, tax_edge_cases
"""

PART_8_POSTS = [
    # 7. banking_problems - Post 2
    {
        "category": "banking_problems",
        "title": "Top 10 Bank Account Freezes, Cyber Cell Notices & KYC Update Blockers Resolved",
        "intro_p1": "Bank account liens and debit freezes triggered by Cyber Cell notices or re-KYC non-compliance cause severe financial disruption for Indian account holders.",
        "intro_p2": "Resolving bank liens requires interfacing with investigating officers, submitting KYC verification documents, and filing RBI Ombudsman complaints.",
        "items": [
            ("Cyber Cell Notice Account Lien Clearance Protocol", "Source: State Cyber Police | Action: Contact IO | Requirement: Proof of Legitimate Income", "Police place lien on account due to suspect P2P or crypto transaction chain.", "Request bank for Cyber Police Station name, Crime No, and IO phone number.", "Submit bank statements and invoice proofs to IO to obtain NOC.", "Bank removes lien upon receiving official NOC email from Cyber Cell."),
            ("Re-KYC Account Debit Block Resolution", "Mandate: RBI Master Direction | Window: Every 2-10 Years | Option: Video KYC / Netbanking", "Banks block debit transactions if periodic re-KYC is not updated.", "Submit self-declaration online if address and details remain unchanged.", "Visit home branch with Aadhaar and PAN card for physical re-KYC.", "Video KYC (V-KYC) facility enables remote re-verification."),
            ("Inoperative / Dormant Account Activation Process", "Condition: No Customer Txn for 2 Years | Rule: Zero Activation Fee | TAT: 24 Hours", "Accounts with no transaction for 2 years classified as dormant.", "Submit fresh KYC documents and passbook copy to home branch.", "Perform single micro-deposit transaction to reactivate account.", "Banks prohibited from charging any fee for activating dormant accounts."),
            ("Resolving Post-Death Deceased Account Claim Procedures", "Limit: Up to ₹5 Lakhs without Probate | Form: Claim Form 14 | Timeline: 15 Days", "Nominee submits death certificate and ID proof for swift balance transfer.", "Without nomination, legal heirs submit indemnity bond and survivor certificate.", "Claims up to ₹5 Lakhs settled without probate or succession certificate.", "Ensure valid nominee is updated in all savings and FD accounts."),
            ("Unfreezing Accounts Blocked Due to PAN-Aadhaar Non-Linking", "Status: Inoperative PAN | Rule: Higher TDS Deduction | Remedy: Link PAN & Pay Penalty", "Unlinked PAN card renders bank account non-compliant under IT rules.", "Bank deducts TDS at higher 20% rate on interest income.", "Link PAN with Aadhaar on IT portal and inform bank branch.", "Update bank record once PAN status shows active on e-Filing portal."),
            ("High-Value Foreign Inward Remittance (FIRC) Hold Resolution", "Regulation: FEMA Compliance | Document: FIRC / Purpose Code | Action: Submit Purpose Declaration", "Banks hold incoming international wire transfers until Purpose Code is declared.", "Select correct Purpose Code (e.g. P0802 for software export).", "Bank issues e-FIRC (Foreign Inward Remittance Certificate) via EDPMS.", "Essential document for GST zero-rated export tax compliance."),
            ("Major / Minor Account Conversion upon Turning 18", "Requirement: Fresh KYC & Signature Update | Authority: RBI Deposit Rules | Form: Minor to Major", "Account frozen when minor account holder turns 18 years old.", "Submit fresh PAN, Aadhaar, and new specimen signature at branch.", "Guardian's joint operational authority terminated upon conversion.", "Issues fresh cheque book and debit card in account holder's name."),
            ("Resolving Accounts Frozen Due to Court Garnishee Orders", "Authority: Civil Court Order | Scope: Specified Debt Amount | Legal Remedies", "Court attaches bank account balance to recover judicial decree debts.", "Lien applies ONLY up to exact amount specified in court order.", "Excess balance above court order remains fully operational.", "Engage legal counsel to challenge or deposit disputed amount in court."),
            ("Clearing Fraudulent Account Block Flagged by CIBIL / CEX", "Source: Credit Bureau Fraud Flag | Action: Dispute Resolution | TAT: 30 Days", "Wrong identity match flags bank account under fraud monitoring radar.", "File dispute ticket on CIBIL or Experian portal with valid identity proof.", "Bank conducts manual audit and issues clearance certificate.", "Monitor annual free credit reports to catch identity mis-matches early."),
            ("RBI Ombudsman Escalation for Delayed Lien Removal", "Portal: RBI CMS | Rule: 30-Day Resolution Limit | Penalty: Bank Compensation", "If bank fails to remove invalid lien within 30 days of submitting NOC, alert RBI.", "File online complaint on RBI CMS portal citing loss of access.", "RBI directs bank to remove lien and pay compensation for wrongful freeze.", "Attach copy of Cyber Cell NOC and written bank branch receipts.")
        ]
    },

    # 7. banking_problems - Post 3
    {
        "category": "banking_problems",
        "title": "Top 10 Dormant Account Recovery & Unclaimed Deposit (UDGAM) Claim Processes",
        "intro_p1": "Inoperative bank accounts and unclaimed fixed deposits across Indian banks run into tens of thousands of crores. The RBI UDGAM portal simplifies locating and claiming lost family deposits.",
        "intro_p2": "Claiming unclaimed deposits requires verifying bank master lists, submitting legal heir certificates, and filing indemnity bonds with bank branches.",
        "items": [
            ("Searching Unclaimed Deposits on RBI UDGAM Portal", "Portal: udgam.rbi.org.in | Coverage: 30+ Major Banks | Input: Name, PAN, DOB", "Register on RBI UDGAM (Unclaimed Deposits - Gateway to Access information) portal.", "Search across participating commercial banks using owner name and PAN/Aadhaar.", "Displays Unclaimed Deposit Reference Number (UDRN) and bank name.", "Covers savings accounts, FDs, RDs, and demand drafts unpaid for 10+ years."),
            ("Understanding Deaf (Depositor Education and Awareness Fund)", "Authority: RBI DEAF Cell | Transfer Window: 10 Years | Rule: Principal + Interest Refundable", "Balances unclaimed for 10 years transferred from bank to RBI DEAF fund.", "Depositors retain full legal right to claim balance at any time.", "RBI refunds principal plus accrued interest through home bank branch.", "No loss of funds occurs even after transfer to DEAF."),
            ("Submitting Physical Claim Dossier to Home Bank Branch", "Requirement: UDRN Number + KYC | Documents: Aadhaar, PAN, Passbook | Verification: Branch Head", "Take UDRN search printout to nearest branch of specific bank.", "Submit claim application along with original passbook/FD receipt and KYC.", "Branch verifies records against legacy ledger archives.", "Process takes 7-14 working days for balance transfer to active account."),
            ("Claiming Unclaimed Accounts Belonging to Deceased Relatives", "Category: Legal Heir Claim | Documents: Death Cert, Legal Heir Cert, Indemnity Bond | Rule: Zero Penalty", "Legal heirs submit death certificate and legal heirship certificate.", "If claim value exceeds ₹5 Lakhs, bank demands probate or succession certificate.", "Two independent guarantors sign indemnity bond at bank branch.", "Bank releases funds to joint legal heir account or designated nominee."),
            ("Resolving Name Discrepancies in Legacy Bank Records", "Issue: Spelling Error in Old Records | Solution: Gazetted Affidavit / CA Cert | Action: Manual Verification", "Old physical ledgers often contain spelling variations or missing surnames.", "Submit notarized affidavit confirming single and same person identity.", "Cross-reference old address details with old passport or ration card.", "Branch manager verifies legacy signature registers."),
            ("Recovering Unclaimed Fixed Deposits (FDs) and Reinvestments", "Status: Matured Unclaimed FD | Rule: Savings Interest Rate | Claim: Re-issue or Cashout", "Matured FDs left unclaimed earn interest at prevailing savings account rate.", "Submit original physical FD receipt (FD Certificate) to branch.", "If original FD receipt lost, submit Form L-106 indemnity bond.", "Choose between instant bank credit or booking fresh term deposit."),
            ("Claiming Unclaimed Dividends & Shares from IEPF Portal", "Portal: iepf.gov.in | Authority: IEPF Authority | Form: Form IEPF-5 | Coverage: Corporate Shares", "Unclaimed company dividends and shares after 7 years transferred to IEPF.", "File online Form IEPF-5 on MCA portal with NSDL/CDSL Demat details.", "Submit physical verification dossier to company Nodal Officer.", "IEPF authority transfers shares back to Demat account."),
            ("Tracing Lost Bank Accounts of Pre-CBS Era (Before 2005)", "Challenge: Pre-Digital Paper Ledgers | Method: Archive Ledger Search | Location: Legacy Branch", "Pre-2005 bank accounts were maintained in physical paper ledgers.", "Identify original branch code and submit old account number/passbook.", "Branch archivists locate physical ledger folio in bank vault.", "Old account migrated into modern Core Banking System (CBS) for payout."),
            ("Claiming Unclaimed Demand Drafts (DD) & Banker's Cheques", "Validity: 3 Months | Rule: Refund to Buyer Account | Action: Revalidation / Cancellation", "Demand drafts un-encashed after 3 months can only be refunded to purchaser.", "If purchaser lost DD copy, file cancellation application with bank.", "Unclaimed DDs older than 10 years searchable on UDGAM portal.", "Money credited back to purchaser's active bank account."),
            ("Tracking Progress of Unclaimed Deposit Claims Online", "Ref: Claim Tracking ID | Service: Bank Nodal Officer | Escalation: Banking Ombudsman", "Collect acknowledgment receipt containing claim reference number from branch.", "Track settlement status on bank official unclaimed deposit portal.", "If branch delays processing beyond 30 days, submit complaint to Nodal Officer.", "Escalate to RBI Ombudsman if claim remains unpaid past 45 days.")
        ]
    }
]
