"""
Part 16 of 39 Authentic Indian Top 10 Posts
Category: can_i_carry (Posts 1, 2, 3)
"""

PART_16_POSTS = [
    # 13. can_i_carry - Post 1
    {
        "category": "can_i_carry",
        "title": "Top 10 Luggage Rules & Prohibited Items for Domestic Indian Airline Flights (DGCA)",
        "intro_p1": "Navigating DGCA aviation security guidelines for domestic flights in India requires knowing exact weight limits, power bank carry-on rules, and prohibited cabin items.",
        "intro_p2": "Complying with airport security requires verifying power bank milliampere-hour (mAh) limits, liquid container sizes, and checked baggage dimensions.",
        "items": [
            ("Power Bank Carry-On Rules & Wh Capacity Limits", "Status: Hand Luggage ONLY | Prohibition: Strictly Banned in Checked Baggage | Limit: 100Wh (27,000 mAh)", "Power banks, lithium spare batteries, and e-cigarettes are STRICTLY PROHIBITED in checked luggage.", "Must carry power banks inside hand baggage only.", "Cap limit is 100Wh (approx 27,000 mAh at 3.7V); batteries 100Wh-160Wh require airline approval.", "Power banks exceeding 160Wh are completely banned on passenger aircraft."),
            ("Liquid, Aerosol & Gel (LAG) Limits for Domestic Cabin Baggage", "Cabin Container Limit: 100 ml per item | Total Limit: 1 Liter Transparent Bag | Checked: Unlimited", "Liquids, gels, lotions, and aerosols in cabin baggage must be in containers of 100 ml or less.", "All 100 ml containers must fit inside a single transparent resealable 1-liter bag.", "Containers larger than 100 ml are confiscated at CISF security screening, even if half empty.", "Pack full-sized shampoos, perfume bottles, and sunscreen in checked luggage."),
            ("Domestic Airlines Checked Baggage Allowance & Excess Weight Fees", "Free Weight Limit: 15 kg (Economy) | Hand Baggage Limit: 7 kg | Excess Fee: ₹550/kg", "Standard domestic economy tickets allow 15 kg checked baggage per passenger.", "Hand baggage limit is strictly 1 laptop bag/handbag up to 7 kg.", "Air India offers higher 20-25 kg checked baggage allowance.", "Pre-book excess baggage online 6 hours prior to save 50% over airport counter rates."),
            ("Prohibited Items in Cabin Baggage (Sharp Objects, Tools & Sporting Gear)", "Prohibited: Scissors (>6cm), Pocket Knives, Screw Drivers, Cricket Bats | Action: Confiscation", "Sharp metallic objects, Swiss army knives, scissors with blades >6cm are banned in cabin bags.", "Tools (wrenches, pliers, drill bits) and sporting bats/clubs must go into checked baggage.", "Confiscated items at CISF security gates are permanently destroyed or auctioned.", "Pack multi-tools, nail clippers, and sporting equipment in checked suitcases."),
            ("Carrying Alcohol & Alcoholic Beverages on Domestic Flights", "Status: Checked Baggage ONLY | Limit: 5 Liters per Passenger | ABV Limit: 24% to 70% ABV", "Alcoholic beverages (24% to 70% ABV) permitted in checked baggage up to 5 liters per passenger.", "Liquors under 24% ABV (beer, wine) have no DGCA quantity limit within checked weight allowance.", "Carrying open alcohol bottles or consuming alcohol on board is a punishable offense.", "Pack glass alcohol bottles in bubble wrap inside hardshell checked luggage."),
            ("Carrying Fresh Food, Spices, Pickles & Ghee", "Cabin Status: Ghee & Pickles Banned in Cabin | Checked Status: Permitted in Sealed Container", "Pickles, ghee, oil, and liquid food items strictly prohibited in cabin hand baggage.", "Permitted in checked luggage if packed in leak-proof sealed plastic containers.", "Dry snacks (sweets, biscuits, dry fruits) allowed in cabin hand baggage.", "Wrap pickle jars in multiple sealed polythene bags to prevent grease damage."),
            ("Transit Rules for Coconut (Dry Copra) Prohibition", "Status: Strictly Banned in Cabin & Checked Baggage | Reason: Highly Flammable Solid", "Dry coconut (Copra) is classified as a dangerous flammable solid under DGCA rules.", "STRICTLY BANNED in both hand cabin baggage AND checked baggage.", "Contains high oil content prone to spontaneous combustion under pressure.", "Fresh green coconuts with water also banned due to liquid volume limits."),
            ("Carrying Firearms, Matchboxes & Lighter Regulations", "Lighters: Strictly Banned | Matchbox: 1 Safety Matchbox on Person | Firearms: License + Security Fee", "Lighters and butane torches are completely banned in both cabin and checked baggage.", "One small safety matchbox permitted on person (pocket), but not inside hand bags.", "Licensed firearms/ammunition require 24h prior airline notice, valid license, and ₹5000 handling fee.", "Surrender firearms at airline security counter before main check-in."),
            ("Musical Instruments as Cabin vs Checked Baggage", "Small Instruments: Violin/Flute (Cabin) | Large: Guitar/Cello (Extra Seat / Hardshell)", "Small musical instruments (flute, violin) can replace standard 7 kg hand bag.", "Guitars require purchasing an extra seat or packing in flight-ready hardshell case for checked transit.", "Loosen instrument strings before flight to prevent bridge damage from cabin pressure drops.", "Label instrument case fragile at airline check-in counter."),
            ("Carrying Medical Equipment (CPAP, Oxygen Concentrators & Insulin)", "Approval: Doctor Certificate + Airline NOC | CPAP: Allowed Free | Battery: Dry Cell", "CPAP machines, nebulizers, and portable oxygen concentrators (POC) allowed on board free.", "Must carry medical certificate from registered doctor explaining equipment need.", "Insulin pens and needles permitted in cabin with valid doctor prescription.", "Inform airline disability customer care desk 48 hours prior to flight date.")
        ]
    },

    # 13. can_i_carry - Post 2
    {
        "category": "can_i_carry",
        "title": "Top 10 Indian Railway Baggage Allowance Rules, Excess Weight Fees & Pet Transit",
        "intro_p1": "Indian Railways specifies luggage weight limits per coach class and regulates carrying pets, bicycles, and commercial goods inside passenger compartments.",
        "intro_p2": "Navigating railway luggage rules requires understanding luggage office booking procedures, pet dog coupe allocation rules, and excess baggage fee slabs.",
        "items": [
            ("Free Luggage Allowance by Train Class & Marginal Allowance", "1st AC: 70 kg | 2nd AC / Executive: 50 kg | 3rd AC / CC: 40 kg | Sleeper: 40 kg", "First AC passengers get maximum 70 kg free baggage allowance per ticket.", "2nd AC and Executive Class allow 50 kg; 3rd AC, Chair Car, and Sleeper allow 40 kg.", "Marginal allowance grants extra 10-15 kg buffer before imposing excess luggage penalty.", "Dimensions must not exceed 100cm x 60cm x 25cm."),
            ("Booking Excess Baggage & Luggage Van (Parcel Office) Rules", "Rate: 1.5x Parcel Rate for Excess | Action: Book at Luggage Office | Penalty: 6x Rate if Caught", "Luggage exceeding free allowance must be booked at station Luggage/Parcel Office.", "Excess baggage booked in advance charged at standard parcel rate.", "Unbooked excess luggage detected by ticket collector on train penalized at 6x rate.", "Book heavy trunks at parcel office 2 hours before train departure."),
            ("Rules for Travelling with Pet Dogs & Cats on Indian Railways", "Class: 1st AC / Executive (Full Coupe/Cabin) | Booking: Parcel Counter | Alternate: Luggage Van", "Pet dogs allowed inside passenger coach ONLY in 1st AC / Executive Class if booking entire coupe (2-berth) or cabin (4-berth).", "Requires veterinary fit-to-travel certificate and rabies vaccination card.", "If traveling in 2AC/3AC, pets must travel in dog box inside Brake Van/Luggage Van.", "Submit written request to Chief Reservation Supervisor for 1st AC coupe allotment."),
            ("Carrying Bicycles, Folding Cycles & Two-Wheelers on Trains", "Folding Cycle: Cabin Luggage | Motorbike: Parcel Van Packing | Requirement: Empty Petrol Tank", "Folding bicycles fitting luggage rack dimensions permitted inside coach as personal luggage.", "Standard bicycles and motorcycles must be booked as parcel cargo in Luggage Van.", "Motorcycle petrol tank must be COMPLETELY DRAINED before parcel booking.", "Carrying motorbike with petrol attracts heavy criminal penalty under Railway Act."),
            ("Prohibited & Hazardous Items on Indian Railways", "Prohibited: Explosives, Crackers, Gas Cylinders, Acid, Kerosene | Penalty: 3 Yrs Jail / ₹1,000", "Carrying inflammable goods (firecrackers, gas cylinders, petrol, acid) strictly prohibited.", "Violators prosecuted under Section 164 of Indian Railways Act 1989.", "Imprisonment up to 3 years or fine up to ₹1,000 or both.", "RPF conducts surprise luggage scanning at major railway station entry gates."),
            ("Carrying Commercial Goods & Merchandise in Passenger Coaches", "Rule: Personal Effects Only | Penalty: Commercial Parcel Rate + Penalty | Action: Seizure", "Passenger coaches meant exclusively for personal travel luggage.", "Carrying commercial merchandise bundles inside AC/Sleeper coaches is illegal.", "TTE penalizes commercial traders carrying trade goods in passenger compartments.", "Book commercial merchandise via Indian Railways Freight/Parcel booking portal."),
            ("Luggage Storage Dimensions & Under-Berth Space Rules", "Dimensions: Max 100 cm x 60 cm x 25 cm | Location: Under Lower Berth | Right: Berth Passenger Priority", "Baggage stored under lower berth must not obstruct aisle walking space.", "Passenger holding lower berth has priority right to under-berth storage space.", "Oversized trunks exceeding 100cm x 60cm x 25cm must be booked in brake van.", "Keep high-value laptops and handbags near your headrest area."),
            ("Cloak Room & Station Luggage Locker Rules", "Requirement: Confirmed Train Ticket + Lockable Bag | Fee: ₹30-50 per 24 Hrs | Max Stay: 7 Days", "Major railway stations offer Cloak Room facility for short-term luggage storage.", "Must produce confirmed train ticket and government photo ID.", "Luggage must be securely locked with physical lock; open bags rejected.", "Maximum storage duration is 7 days."),
            ("Carrying Food, Gas Stoves & Cooking Equipment", "Permitted: Packed Food, Electric Kettle | Prohibited: Gas Stoves, Kerosene Burners", "Packed cooked food, dry snacks, and electric kettles permitted.", "Carrying portable gas stoves, LPG cylinders, or kerosene burners is illegal.", "Boiling food using open flame or gas stove inside train coach is a criminal offense.", "Utilize IRCTC e-catering service to order fresh food delivered to your seat."),
            ("Claiming Compensation for Lost or Stolen Luggage on Trains", "Action: File GRP FIR Form | Claim: Railway Claims Tribunal (RCT) | Max Claim: ₹100/kg", "If luggage is stolen, request TTE for pre-printed GRP FIR complaint form.", "File formal claim for loss of baggage with Railway Claims Tribunal (RCT).", "Compensation capped at statutory rate unless luggage value was declared during parcel booking.", "Always keep valuable jewelry, cash, and electronics in personal shoulder bag.")
        ]
    },

    # 13. can_i_carry - Post 3
    {
        "category": "can_i_carry",
        "title": "Top 10 Customs Duty Rules for Carrying Laptops, Gold & Electronics into India",
        "intro_p1": "Arriving in India from international flights triggers Customs Duty regulations under Indian Customs Baggage Rules regarding gold jewelry, secondary laptops, and high-value gifts.",
        "intro_p2": "Complying with customs duty requires evaluating Duty-Free allowances, gold import weight limits for male and female travelers, and Red Channel declarations.",
        "items": [
            ("General Duty-Free Free Allowance for Indian Residents & Tourists", "Allowance: ₹50,000 (Resident) | Tourists: ₹15,000 | Duty Rate: 38.5% on Excess", "Indian residents returning from foreign trips enjoy ₹50,000 duty-free baggage allowance.", "Foreign tourists get ₹15,000 duty-free allowance for gifts and personal items.", "Goods exceeding duty-free limit taxed at flat 38.5% customs duty rate.", "Duty-free allowance cannot be pooled across family members for single item."),
            ("Carrying Personal & Secondary Laptops Duty-Free", "Allowance: 1 Used Laptop Free | Requirement: Age > 18 Years | Secondary Laptop: Taxable", "One used laptop/notebook computer imported duty-free per passenger aged 18+.", "Applies over and above standard ₹50,000 general duty-free allowance.", "Carrying a SECOND laptop attracts customs duty if total value exceeds ₹50,000.", "Declare secondary company laptops with employer letter at Red Channel."),
            ("Gold Jewelry Duty-Free Allowance for Men vs Women Travelers", "Stay Requirement: > 1 Year Abroad | Female Cap: 40g (Max ₹1 Lakh) | Male Cap: 20g (Max ₹50,000)", "Passengers living abroad for >1 year can bring gold jewelry duty-free.", "Female passengers: Max 40 grams of gold jewelry (capped at ₹1,000,000 value).", "Male passengers: Max 20 grams of gold jewelry (capped at ₹50,000 value).", "Gold coins and gold bars DO NOT qualify for duty-free allowance; taxed at full duty."),
            ("Customs Duty Rules on Importing Television Sets (Flat Panel TVs)", "Duty Status: NO Exemption | Tax Rate: 38.5% Flat Duty | Base: Invoice Value or Valuation", "Flat panel LCD/LED/OLED televisions DO NOT enjoy any duty-free allowance.", "All imported TVs taxed at flat 38.5% customs duty regardless of size or value.", "Customs assesses TV value based on screen size valuation matrix or purchase receipt.", "Pay customs duty at airport Customs Counter before clearing Green Channel."),
            ("Carrying Foreign Currency & Indian Rupees (Cash vs Traveler's Cheques)", "Forex Limit: $5,000 Cash / $10,000 Total | CDF Form: Required if Exceeded | INR Cap: ₹25,000", "Can bring up to USD 5,000 in physical currency notes without declaration.", "Total forex (cash + traveler cheques) up to USD 10,000 allowed without declaration.", "Exceeding limit requires filing Currency Declaration Form (CDF) upon arrival.", "Carrying Indian currency notes into India capped at ₹25,000 per passenger."),
            ("Alcohol & Cigarette Duty-Free Allowance Caps", "Alcohol Cap: 2 Liters | Cigarettes Cap: 100 Sticks | Cigars: 25 | Tobacco: 125 grams", "Passengers allowed 2 liters of alcoholic liquor or wine duty-free.", "Cigarettes capped at 100 sticks (approx 5 packs); cigars capped at 25.", "Purchases at Duty-Free shops inside Indian arrival halls count within 2L cap.", "Carrying excess alcohol or cigarettes attracts 100%+ customs duty confiscation."),
            ("Declaring High-Value Drones, Cameras & Professional Gear", "Drones: Restricted Category | Permit: WPC / DGCA Approval | Camera: 1 Used Unit Free", "Drones are restricted import items requiring prior WPC (Wireless) and DGCA clearance.", "Carrying undeclared drones leads to instant customs seizure at airport.", "One used professional camera with standard lens allowed duty-free as personal effect.", "Declare expensive cinema cameras under ATA Carnet for temporary exhibition/filming."),
            ("Green Channel vs Red Channel Customs Clearance Protocol", "Green Channel: Zero Dutiable Goods | Red Channel: Dutiable / Restricted Goods | Penalty: 100% Fine", "Walk through Green Channel ONLY if carrying no dutiable, prohibited, or excess goods.", "Walk through Red Channel if carrying excess gold, secondary laptops, or >$5k cash.", "Passing Green Channel with hidden dutiable goods leads to heavy fine and arrest under Customs Act.", "When in doubt, always step into Red Channel to consult Customs Duty Officer."),
            ("Importing Commercial Goods as Passenger Baggage (Trade Quantities)", "Status: Strictly Illegal as Baggage | Penalty: Seizure + Confiscation + Penalties under Customs Act", "Carrying bulk commercial quantities of goods (e.g. 50 iPhones, 100 shoes) is illegal.", "Passenger baggage meant strictly for personal use or non-commercial gifts.", "Commercial goods must be imported via Air Cargo with Bill of Entry.", "Customs seizes trade quantities and issues formal show-cause notices."),
            ("Transfer of Residence (TR) Customs Concessions for Returning NRIs", "Stay Limit: 2+ Years Abroad | Concession: Duty-Free Personal Effects | Allowance: Up to ₹5 Lakhs", "NRIs returning permanently after 2+ years abroad qualify for Transfer of Residence (TR).", "Import used household articles (furniture, clothes, appliances) duty-free up to ₹5 Lakhs.", "Specified luxury items (air conditioner, dishwasher) charged reduced concessional duty.", "Apply for TR clearance with customs handling agent prior to container arrival.")
        ]
    }
]
