"""
Part 5 of 39 Authentic Indian Top 10 Posts
Categories: can_i_queries, what_happens_if, bureaucracy, banking_problems
"""

PART_5_POSTS = [
    # 4. can_i_queries - Post 3
    {
        "category": "can_i_queries",
        "title": "Top 10 Indian 'Can I...' Financial & Investment Rules for NRIs and Residents",
        "intro_p1": "Financial regulations under RBI, FEMA, and SEBI govern how Non-Resident Indians (NRIs) and Indian residents manage bank accounts, stock investments, mutual funds, and overseas money transfers.",
        "intro_p2": "Evaluating financial queries requires consulting Foreign Exchange Management Act (FEMA) provisions, Income Tax Act sections, and RBI circulars.",
        "items": [
            ("Can an NRI continue holding resident Indian bank accounts?", "Legal Status: Strictly Illegal | Authority: FEMA Section 3 | Action: Convert to NRE/NRO", "Holding resident bank accounts after acquiring NRI status violates FEMA.", "Must re-designate existing accounts to NRO (Non-Resident Ordinary) accounts.", "Penalty includes fines up to 3x the un-designated amount.", "Notify bank within 3 months of changing residency status."),
            ("Can I transfer money from NRO account to foreign bank account?", "Legal Status: Permitted up to $1M/yr | Authority: RBI FEMA Guidelines | Requirement: Form 15CA/15CB", "NRIs can repatriate up to USD 1 Million per financial year from NRO account.", "Requires CA certificate (Form 15CB) confirming all Indian taxes are paid.", "NRE account funds are fully repatriable without any dollar limits.", "Obtain Form 15CB from registered Indian CA before wire transfer."),
            ("Can an Indian resident send money abroad for buying foreign stocks?", "Legal Status: Permitted up to $250k/yr | Authority: RBI LRS Scheme | Tax: TCS Applies", "Liberalised Remittance Scheme (LRS) permits residents to send up to USD 250,000 annually.", "Used for overseas stock investments, real estate, education, and travel.", "TCS (Tax Collected at Source) of 20% applies on remittances exceeding ₹7 Lakhs.", "Claim TCS credit while filing annual Indian income tax return."),
            ("Can an NRI invest in Indian stock market directly?", "Legal Status: Permitted | Authority: SEBI & RBI | Route: PIS / Non-PIS Account", "NRIs can trade Indian equities through Portfolio Investment Scheme (PIS) or Non-PIS accounts.", "Must open NRE/NRO Demat and Trading account with SEBI-registered broker.", "Intraday trading is strictly prohibited for NRIs; only delivery trades allowed.", "Use Non-PIS NRO account for trading derivative contracts."),
            ("Can I gift money to foreign relatives tax-free under Indian Income Tax Act?", "Legal Status: Tax-Free for Specified Relatives | Authority: Income Tax Act Section 56(2)(x) | Limit: LRS Ceiling", "Gifts to specified linear relatives (parents, children, siblings) are tax-free.", "Remittance subject to TCS under LRS rules if sent abroad from resident account.", "Non-relatives receiving gifts over ₹50,000 in India face income tax.", "Execute written Gift Deed for all high-value monetary transfers."),
            ("Can an NRI claim home loan tax benefits on Indian property?", "Legal Status: Fully Permitted | Authority: Income Tax Act Section 24 & 80C | Condition: Taxable Income in India", "NRIs can claim deduction up to ₹2 Lakhs on home loan interest under Section 24.", "Principal repayment eligible under Section 80C up to ₹1.5 Lakhs.", "Benefits apply if NRI has taxable income generated within India.", "Set off property loss against rental income in Indian IT return."),
            ("Can I invest in Public Provident Fund (PPF) as an NRI?", "Legal Status: Restricted Continuation | Authority: Ministry of Finance | Rule: No New PPF Accounts", "NRIs cannot open NEW PPF accounts after becoming non-residents.", "Existing PPF accounts opened prior to becoming NRI can continue till 15-year maturity.", "No extension permitted beyond 15-year maturity period for NRIs.", "Maturity proceeds can be credited directly to NRO account."),
            ("Can an Indian resident open a foreign bank account while living in India?", "Legal Status: Permitted under LRS | Authority: RBI FEMA Guidelines | Requirement: Schedule FA Disclosure", "Residents can open foreign bank accounts for holding LRS investments.", "Must disclose foreign bank details in Schedule FA of Income Tax Return.", "Non-disclosure of foreign assets triggers severe Black Money Act penalties.", "Declare all foreign bank accounts annually regardless of balance."),
            ("Can an NRI invest in Indian Mutual Funds without visiting India?", "Legal Status: Permitted | Authority: AMFI / SEBI | Condition: KYC & US/Canada Rules", "NRIs can invest in Indian mutual funds online via paperless e-KYC.", "US and Canada-based NRIs face restrictions due to FATCA compliance.", "Select mutual fund houses (e.g. SBI, HDFC, ICICI) accept US/Canada NRI investments.", "Complete FATCA self-declaration during online onboard process."),
            ("Can I withdraw entire EPF balance when moving abroad permanently?", "Legal Status: Permitted | Authority: EPFO Rules | Condition: 2 Months Unemployment / Settlement Abroad", "Can withdraw full Provident Fund balance upon settling abroad permanently.", "Tax-free if continuous service exceeded 5 years before leaving India.", "Service under 5 years attracts income tax on employer contribution.", "Submit online EPF Form 19 via Universal Account Number (UAN) portal.")
        ]
    },

    # 5. what_happens_if - Post 1
    {
        "category": "what_happens_if",
        "title": "Top 10 'What Happens If...' Railway Scenarios: Lost Tickets, Missed Trains & Refunds",
        "intro_p1": "Indian Railways operates one of the world's largest rail networks, carrying over 22 million passengers daily. Yet when operational glitches occur—from losing your physical ticket to missing a connecting train—passengers are caught off guard.",
        "intro_p2": "Navigating Indian Railways rules requires understanding the IRCTC TDR (Ticket Deposit Receipt) refund process, Commercial Railway Code guidelines, and station master emergency powers.",
        "items": [
            ("What happens if you lose your physical confirmed train ticket before boarding?", "Rule: Duplicate Ticket Issuance | Authority: Indian Railways Commercial Code | Fee: ₹50-100", "Report to Chief Reservation Supervisor before chart preparation with photo ID.", "Duplicate ticket issued upon paying ₹50 (Sleeper) or ₹100 (AC class).", "Full refund granted if original ticket is found before train departure.", "Carry digital screenshot of booking SMS as instant proof."),
            ("What happens if your train is delayed by more than 3 hours?", "Rule: Full Refund without Penalty | Authority: IRCTC TDR Rules | Condition: Ticket Not Traveled", "Eligible for 100% fare refund if train is delayed over 3 hours at starting station.", "Must file TDR online before actual departure of train.", "No cancellation charges deducted for severe railway delay.", "File TDR via IRCTC app before train leaves your boarding station."),
            ("What happens if you miss your train due to a delayed connecting train?", "Rule: Alternative Accommodation / Full Refund | Authority: Combination Ticket Rules | Condition: PNR Linked", "If passenger misses connecting train due to late running of first train, full refund is granted.", "Both PNRs must be linked at time of booking.", "Filing TDR at junction station enables free booking on next available train.", "Always link multi-leg train bookings under single journey profile."),
            ("What happens if your confirmed RAC ticket does not get berth allocation?", "Rule: Seating Berth Granted | Authority: IRCTC Berth Matrix | Right: Half-Berth Sharing", "RAC (Reservation Against Cancellation) guarantees seating access on train.", "TTE must allocate full sleeping berth if confirmed passengers don't show up.", "If no berth opens up, passenger can travel seated legally.", "Check live berth vacancy on TTE handheld terminal during journey."),
            ("What happens if you board a train with a Waitlisted e-Ticket?", "Rule: Strictly Illegal | Authority: Railway Act Section 137 | Penalty: Treated as Ticketless", "Fully waitlisted e-tickets are automatically cancelled after chart preparation.", "Boarding train with cancelled e-ticket leads to ticketless passenger penalty.", "TTE will charge full fare from origin plus ₹250 penalty.", "Cancel waitlisted ticket and book Tatkaal or Tatkaal Special."),
            ("What happens if you fall ill during a long-distance train journey?", "Rule: On-Board Medical Assistance | Authority: Railway Medical Services | Cost: Nominal Doctor Fee", "Inform TTE or dial 139 instantly for medical emergency.", "Railway doctor dispatched to meet train at next major halt station.", "Emergency medicine administered on board for nominal charge.", "Keep RailMadad app installed for priority emergency alerts."),
            ("What happens if your luggage is stolen on an Indian Railways train?", "Rule: GRP FIR Registration | Authority: Government Railway Police (GRP) | Action: Conductor FIR Form", "Inform TTE immediately; conductor carries pre-printed GRP FIR forms.", "No need to disembark train to file police complaint.", "FIR transferred automatically to jurisdiction railway police station.", "Secure all luggage with steel cables and padlocks under lower berth."),
            ("What happens if you accidentally drop your phone on railway tracks?", "Rule: Pole Number Note | Authority: RPF Patrol | Retrieval: Next Station Stop", "Note exact OHE (Overhead Equipment) pole number written on side track posts.", "Inform Railway Protection Force (RPF) at next station halt.", "RPF personnel track pole location and retrieve dropped item.", "Never attempt to jump off moving train to collect fallen items."),
            ("What happens if you get down at a station and the train leaves without you?", "Rule: Luggage Protection by TTE | Authority: Station Master Emergency | Next Action: Board Next Express", "Inform Station Master immediately; they alert TTE on board moving train.", "TTE locks your berth area and hands over luggage at next major junction.", "Station Master issues travel permit to catch up on following express.", "Keep phone, wallet, and ID on your person during quick platform walks."),
            ("What happens if you pull the Emergency Alarm Chain (ACP) without valid reason?", "Rule: Criminal Offense | Authority: Railway Act Section 141 | Penalty: ₹1,000 fine / 1 yr jail", "Chain pulling permitted ONLY for medical emergency, safety threat, or passenger separation.", "Unjustified chain pulling causes severe corridor train delays.", "RPF traces specific coach via mechanical signal indicator.", "Use chain pulling strictly as absolute last resort for life safety.")
        ]
    },

    # 5. what_happens_if - Post 2
    {
        "category": "what_happens_if",
        "title": "Top 10 'What Happens If...' Banking Emergencies: Stuck UPI, Fraud Charges & ATM Glitches",
        "intro_p1": "Digital payment adoption in India leads the world, but system glitches, unauthorized debits, and phishing attempts create panic. Knowing exact regulatory recourse and turnaround times guarantees financial recovery.",
        "intro_p2": "Evaluating banking emergencies requires referencing Reserve Bank of India (RBI) Ombudsman schemes, NPCI TAT circulars, and Cyber Crime reporting protocols.",
        "items": [
            ("What happens if your money is debited via UPI but receiver doesn't get it?", "Rule: Auto-Reversal TAT | Authority: NPCI Guidelines | Penalty: ₹100/day for bank delay", "System failure triggers automatic reversal within T+1 working days.", "If bank fails to credit back within 5 days, bank pays ₹100 per day compensation.", "File grievance on NPCI portal if unresolved past 48 hours.", "Check UPI transaction status on BHIM app before re-sending money."),
            ("What happens if you fall victim to a digital cyber fraud or phishing call?", "Rule: Zero Liability Window | Authority: RBI Fraud Circular & Cyber Helpline 1930 | Golden Window: 3 Hours", "Report to 1930 Cyber Crime Helpline within 3 hours to freeze fraud account.", "Notify bank within 3 days for ZERO customer liability.", "Delaying beyond 3 days increases customer loss liability.", "Immediately block netbanking and debit cards via bank SMS numbers."),
            ("What happens if an ATM debits cash from your account but fails to dispense money?", "Rule: T+5 Days Auto-Credit | Authority: RBI ATM Guidelines | Penalty: ₹100/day after 5 days", "ATM system logs transaction failure and flags auto-reversal.", "Bank must credit money back to customer account within 5 working days.", "₹100 per day penalty payable by bank for every day of delay beyond T+5.", "Save ATM slip and note exact ATM ID number."),
            ("What happens if you accidentally transfer money to the wrong bank account via IMPS/NEFT?", "Rule: Inter-Bank Recovery | Authority: RBI Banking Ombudsman | Action: Branch Manager Recall", "Inform your bank branch immediately with transfer UTR number.", "Remitting bank sends official recall request to recipient bank.", "If recipient refuses consent, legal notice required for recovery.", "Double check account number and IFSC code before authorizing transfer."),
            ("What happens if your bank account is frozen due to Cyber Cell notice?", "Rule: Lien Clearance Protocol | Authority: State Cyber Cell & Bank | Action: Investigating Officer NOC", "Bank places lien on account due to suspect transaction flagged in cyber police chain.", "Must contact specific Cyber Police Station (IO) listed in bank notice.", "Provide legitimate proof of funds to obtain NOC for lien removal.", "Request bank for specific Cyber Cell FIR/Crime number and IO contact."),
            ("What happens if a loan EMI bounces due to insufficient funds?", "Rule: NACH Bounce Charges & CIBIL Impact | Authority: RBI / Credit Bureaus | Charge: ₹250-500", "Bank levies NACH/ECS bounce charge and lender adds late payment fee.", "Delayed payment beyond 30 days negatively impacts CIBIL credit score.", "Persistent default triggers recovery proceedings under SARFAESI Act.", "Maintain adequate buffer balance 2 days prior to EMI auto-debit date."),
            ("What happens if your bank goes into RBI moratorium or liquidation?", "Rule: ₹5 Lakh Insurance Cover | Authority: DICGC Act | Timeline: 90 Days", "DICGC insures bank deposits (savings, FD, RD) up to ₹5 Lakhs per bank.", "Depositors receive insured amount within 90 days of moratorium order.", "Amounts above ₹5 Lakhs settled upon bank asset liquidation.", "Spread large cash reserves across multiple distinct banking licenses."),
            ("What happens if your credit card is used for unauthorized international transactions?", "Rule: Immediate Card Block & Dispute | Authority: RBI Security Circular | Safety: Turn off Int'l Usage", "Block card immediately via mobile app or customer support.", "File credit card dispute form within 30 days for chargeback.", "Turn off international online transactions on card app when not traveling.", "Disable international online usage by default in card settings app."),
            ("What happens if an online merchant double-charges your debit card?", "Rule: Merchant Chargeback | Authority: Visa/Mastercard/RuPay Rules | TAT: 7-14 Days", "Merchant system initiates refund for duplicate authorization hold.", "If merchant fails, file chargeback dispute with issuing bank.", "Bank issues temporary credit while investigating dispute.", "Provide invoice copy and bank statement showing double debit."),
            ("What happens if your fixed deposit (FD) matures and you don't renew it?", "Rule: Savings Interest Rate | Authority: RBI FD Guidelines | Rate: Lower of Savings or Original FD", "Unclaimed matured FDs earn savings account interest rate or original FD rate (whichever is lower).", "Auto-renewal facility prevents loss of higher term deposit yields.", "Funds remain safe in bank account until instructions received.", "Enable auto-renewal option while booking fixed deposits online.")
        ]
    }
]
