"""
Part 12 of 39 Authentic Indian Top 10 Posts
Categories: error_dictionary, remote_work_logistics
"""

PART_12_POSTS = [
    # 10. error_dictionary - Post 1
    {
        "category": "error_dictionary",
        "title": "Top 10 Government Portal Error Codes (Income Tax, MCA, EPFO) & How to Bypass Them",
        "intro_p1": "Accessing Indian government digital portals during peak filing seasons frequently results in obscure error codes, portal timeouts, and failed cryptographic signatures.",
        "intro_p2": "Bypassing government web errors requires understanding digital signature certificate (DSC) drivers, Java runtime permissions, browser cache clearing, and server load balances.",
        "items": [
            ("Income Tax Portal Error: 'DSC Not Registered' or 'EMBridge Connection Failed'", "Cause: Token Driver / Port Block | Fix: Reinstall emBridge & Run as Admin | Port: 8443 / 26900", "Occurs when tax portal fails to detect USB Digital Signature Certificate token.", "Download latest emBridge service from Income Tax portal.", "Ensure port 8443 or 26900 is unblocked by firewall.", "Run Chrome browser in Administrator mode and clear Java cache."),
            ("EPFO Portal Error: 'Member Name / DOB / Gender Mismatch with Aadhaar'", "Cause: UAN Data Mismatch | Fix: Joint Declaration Form / Online Modification | TAT: 7 Days", "EPF claim fails if UAN profile details differ slightly from Aadhaar database.", "Submit online modification request on EPFO Unified Member Portal.", "Requires employer approval via digital signature on portal.", "Ensure Aadhaar linked phone number receives OTP during request."),
            ("MCA Portal Error: 'System Unavailable / Internal Server Error 500'", "Cause: V3 Portal Server Overload | Fix: Clear Cache / Incognito / Off-Peak Hours | Window: 10 PM - 7 AM", "Occurs during peak ROC filing dates on MCA v3 portal.", "Use Chrome Incognito mode with cleared SSL state.", "File forms during off-peak hours (late evening or early morning).", "Ensure PDF forms are filled using Adobe Acrobat Reader DC only."),
            ("Parivahan Portal Error: 'Payment Pending / Transaction Timed Out'", "Cause: Gateway Timeout | Fix: Check Payment Status / Wait 45 Mins | Action: Re-verification", "Money debited from bank but Parivahan portal shows unpaid status.", "Click 'Check Payment Status' link under Citizen Services.", "Wait 45 minutes for automated gateway reconciliation before retrying.", "Avoid initiating duplicate payments within 2 hours."),
            ("Passport Seva Portal Error: 'Appointment Slot Exceeded / Max Attempts Reached'", "Cause: Session Locking | Fix: Log Out & Clear Cookies | Wait: 24 Hours", "Occurs when refreshing appointment booking page rapidly.", "Portal locks user account for 24 hours to prevent bot scraping.", "Use stable broadband connection and log in 5 minutes before slot opening.", "Select alternative PSK or POPSK location in same pin code zone."),
            ("Income Tax Error: 'Invalid XML / JSON Schema Validation Failed'", "Cause: Schema Version Outdated | Fix: Download Latest Offline Utility | Action: Re-generate JSON", "Generated ITR JSON file rejected by portal during upload.", "Ensure offline utility matches exact version updated after Union Budget.", "Re-import financial data into fresh utility copy and re-generate JSON.", "Do not manually edit JSON code tags in notepad."),
            ("GSTN Portal Error: 'Summary GSTR-3B Not Matching GSTR-1 Data'", "Cause: Table 3.1 Variance | Fix: Re-compute Liability | Action: Manual Adjustment", "Portal blocks GSTR-3B submission if outward tax liability differs from filed GSTR-1.", "Click 'Re-compute Liability' button on GST dashboard.", "Ensure outward supply numbers match filed GSTR-1 values.", "File GSTR-1 amendments in subsequent tax period if errors exist."),
            ("EPFO Error: 'Invalid Signature / Token Certificate Error during E-Sign'", "Cause: Java Security | Fix: Add EPFO URL to Java Exception Site List | Setting: High", "E-sign process fails when employer signs EPF claims with DSC.", "Open Java Control Panel -> Security Tab -> Edit Site List.", "Add 'https://unifiedportal-emp.epfindia.gov.in' to Java Exception list.", "Set Java security level to High instead of Very High."),
            ("Vahan RTO Error: 'Vehicle Chassis Number Already Exists in Database'", "Cause: Duplicate Entry / RTO Typo | Fix: RTO Data Correction Application | Action: Physical File Check", "Prevents online RC renewal or transfer due to previous RTO clerical error.", "Submit physical application to home RTO with original pencil chassis impression.", "RTO officer updates master Vahan database.", "Attach original RC book copy showing correct chassis number."),
            ("DigiLocker Error: 'Document Fetch Failed / URI Not Found'", "Cause: Partner API Downtime | Fix: Unlink & Re-link Partner Account | Action: Re-enter Aadhaar OTP", "DigiLocker fails to fetch driving license, marksheets, or vehicle RC.", "Ensure name on partner database matches DigiLocker profile exactly.", "Delete cached document and attempt fresh fetch via Aadhaar OTP.", "Re-verify partner issuer status on DigiLocker status dashboard.")
        ]
    },

    # 10. error_dictionary - Post 2
    {
        "category": "error_dictionary",
        "title": "Top 10 Indian Payment Gateway & Netbanking Errors Explained (Razorpay, SBI, HDFC)",
        "intro_p1": "E-commerce transactions and bill payments frequently fail due to payment gateway session timeouts, 3D Secure OTP delays, and interbank switch errors.",
        "intro_p2": "Resolving payment errors requires understanding merchant webhook retries, card network authentication protocols, and refund reconciliation cycles.",
        "items": [
            ("Razorpay / PayU Error 'BAD_REQUEST_ERROR / Transaction Timed Out'", "Cause: Session Expiry / Slow Network | Action: Clear Browser Storage & Retry", "Occurs when checkout modal loses connection to gateway server.", "Do not refresh page while 3D Secure OTP screen is processing.", "Switch from Wi-Fi to 5G mobile hotspot if latency exceeds 200ms.", "Check bank SMS before initiating duplicate payment."),
            ("SBI Netbanking Error 'Mandatory Fields Missing / Invalid Session Token'", "Cause: Stale Session Cookies | Fix: Clear SBI Site Cookies / Restart Browser", "SBI Online netbanking drops session state during multi-step transfers.", "Disable browser auto-fill extensions on netbanking login page.", "Use Edge or Chrome in Private Window mode.", "Log out completely before opening new transaction tabs."),
            ("HDFC Netbanking Error 'Customer ID Blocked / Invalid Credentials'", "Cause: 3 Failed Password Attempts | Fix: Forgot Customer ID / IPIN Reset", "Entering wrong IPIN 3 times locks netbanking for 24 hours.", "Reset IPIN online instantly using debit card number and ATM PIN.", "Ensure mobile number receives OTP for authorization.", "Unlocks access without visiting physical branch."),
            ("ICICI iMobile Error 'Device Binding Failed / Mobile Number Mismatch'", "Cause: Dual SIM Slot Switch | Fix: Move Registered SIM to Slot 1", "iMobile app checks hardware binding against registered SIM slot.", "Ensure registered mobile number SIM is placed in primary SIM Slot 1.", "Turn off Wi-Fi during initial SMS verification setup.", "Grant SMS permissions to iMobile app in Android settings."),
            ("Payment Gateway Error '3D Secure Authentication Failed / Invalid OTP'", "Cause: Telecom OTP Delay / Network Jitter | Fix: Resend OTP via Voice Call", "Bank fails to deliver SMS OTP within 120-second gateway window.", "Click 'Resend OTP via Voice Call' option if SMS is delayed.", "Check if SMS inbox is full or spam filter blocked bank shortcode.", "Ensure international roaming is enabled if transacting abroad."),
            ("Razorpay Error 'PAYMENT_FAILED / Bank Issuer Decline'", "Cause: Daily Card Limit Exceeded / International Usage Disabled | Action: Card App Setting", "Card issuer declines charge due to security limit or disabled channel.", "Open card mobile app and verify Online / E-commerce usage toggle is ON.", "Increase daily transaction limit on card settings dashboard.", "Try alternative RuPay or Visa card."),
            ("Paytm Gateway Error 'Vault Token Expired / Saved Card Failed'", "Cause: RBI Card Tokenization Expiry | Action: Delete & Re-save Card Token", "Saved credit/debit card token fails during checkout verification.", "Delete saved card from merchant checkout screen.", "Re-enter 16-digit card number, expiry, and CVV to generate fresh token.", "Complies with RBI mandatory tokenization framework."),
            ("Axis Bank Netbanking Error 'ERR_CONNECTION_RESET / SSL Handshake Failed'", "Cause: TLS Protocol Mismatch | Fix: Update Browser / Disable Antivirus Inspection", "Antivirus software SSL inspection interferes with bank encryption.", "Temporarily pause third-party antivirus web shield during payment.", "Ensure browser supports TLS 1.3 encryption protocol.", "Clear SSL State in Windows Internet Properties."),
            ("BillDesk Error 'Transaction Under Processing / Status Awaited'", "Cause: Interbank Settlement Delay | Action: Wait 24 Hours for Reconciliation", "Payment status remains ambiguous after money is debited from bank.", "Merchant receives webhook update within 2 hours.", "Do not re-pay bill immediately; check status on merchant portal.", "Refund automatically triggered if transaction fails reconciliation."),
            ("UPI Gateway Error 'Transaction Amount Exceeds Merchant Limit'", "Cause: Merchant VPA Tier Limit | Action: Use Netbanking / Debit Card", "Small QR merchants cannot accept single UPI payments exceeding ₹20,000.", "Use netbanking or credit card for high-value purchases.", "Split billing across multiple merchant QR handles if allowed.", "Ensures compliance with NPCI merchant category limits.")
        ]
    }
]
