"""
Part 7 of 39 Authentic Indian Top 10 Posts
Categories: bureaucracy, banking_problems, credit_cards, tax_edge_cases
"""

PART_7_POSTS = [
    # 6. bureaucracy - Post 3
    {
        "category": "bureaucracy",
        "title": "Top 10 Provident Fund (EPF), UAN & Pension Transfer Protocols Simplified",
        "intro_p1": "Managing Employee Provident Fund (EPF) transfers when switching jobs in India requires mastering the Universal Account Number (UAN) digital portal. Resolving employer approval roadblocks guarantees pension continuity.",
        "intro_p2": "Navigating EPFO protocols requires referencing Employees' Provident Funds Scheme 1952, Form 13 transfer rules, and EPS pension certificate guidelines.",
        "items": [
            ("How to activate Universal Account Number (UAN) online?", "Portal: EPFO Member Sevottam | Requirement: Mobile + Aadhaar | TAT: Instant", "Visit EPFO Member Portal and click 'Activate UAN'.", "Enter UAN, Member ID, Aadhaar number, name, and date of birth.", "OTP sent to Aadhaar-linked mobile number completes activation.", "Set strong password and verify email address immediately."),
            ("How to transfer EPF online when switching jobs (Form 13)?", "Portal: Unified Member Portal | Feature: One Member One EPF Account | Approval: Previous/Current Employer", "Log in to UAN Member Portal and select 'One Member - One EPF Account (Transfer Request)'.", "Verify previous employment details and select attesting employer (current or previous).", "Employer approves digital Form 13 transfer via Digital Signature (DSC).", "Track transfer claim status under 'View Claim Status' tab."),
            ("How to correct Date of Exit on EPF portal if previous employer failed to update?", "Portal: UAN Portal | Feature: Mark Exit | Limitation: 2 Months Post Leaving", "Employees can self-mark Date of Exit 2 months after leaving previous job.", "Select 'Manage' -> 'Mark Exit' on UAN Portal.", "Select reason for leaving (short service, health, permanent departure).", "Date of Exit must fall in the month last PF contribution was remitted."),
            ("How to merge multiple UANs into a single active UAN number?", "Portal: EPFO Portal / Employer Helpdesk | Process: UAN Consolidation | Protection: Prevents Block", "Employees having multiple UANs must request consolidation under active UAN.", "Mail EPFO at uanepf@epfindia.gov.in or report to current employer.", "Previous UAN balance transferred to current active UAN.", "Only one UAN per individual is legally permitted under EPFO rules."),
            ("How to withdraw EPF balance online for medical, house purchase, or marriage advance?", "Portal: UAN Portal | Form: Form 31 (Partial Withdrawal) | TAT: 3-5 Working Days", "Submit Form 31 online for non-refundable partial PF advance.", "Eligible for house purchase (5 yrs service), illness, or marriage (7 yrs service).", "Money credited directly to bank account linked with Aadhaar.", "No physical documents required for online partial withdrawal."),
            ("How to claim EPS Pension Scheme certificate (Form 10C)?", "Portal: EPFO Portal | Form: Form 10C | Condition: Under 10 Years Service", "Form 10C issued for pension withdrawal or scheme certificate.", "Scheme Certificate retains pension service record for future employment.", "Mandatory if total service is under 10 years and employee leaves workforce.", "Continuous 10 years service unlocks monthly pension eligibility at age 58."),
            ("How to resolve 'Name / Father Name Mismatch' blocking EPF claim?", "Portal: Joint Declaration Portal | Approval: Employer & Field Office | Document: Aadhaar / PAN", "Submit online Joint Declaration request on UAN portal.", "Employer signs request digitally and forwards to regional EPFO field office.", "Attach Aadhaar, PAN card, and school leaving certificate copy.", "Field officer updates master EPFO database within 7-14 days."),
            ("How to file an EPF Grievance on EPFiGMS portal for delayed claims?", "Portal: EPFiGMS Portal | Resolution Window: 15 Days | Escalation: Regional PF Commissioner", "Log onto epfigms.gov.in and register complaint under UAN number.", "Upload claim acknowledgement receipt and bank statement copy.", "Regional PF Commissioner reviews and resolves grievance within 15 days.", "Track grievance registration number online for real-time status."),
            ("How to check EPF Passbook balance via SMS and Missed Call?", "Number: 9966044425 (Missed Call) / 7738299899 (SMS) | Requirement: Activated UAN", "Give missed call to 9966044425 from registered mobile number.", "SMS format 'EPFOHO UAN ENG' sent to 7738299899 returns balance.", "Provides instant breakdown of employee, employer, and pension contributions.", "Requires UAN to be linked with Aadhaar, PAN, and bank account."),
            ("How to update bank account details (KYC) on UAN portal?", "Portal: Member Portal | Section: Manage KYC | Approval: Employer DSC", "Log in and navigate to 'Manage' -> 'KYC' -> Select 'Bank'.", "Enter bank account number and IFSC code; system validates via bank API.", "Employer approves pending bank KYC using Digital Signature Certificate.", "Ensure bank account name matches UAN profile name exactly.")
        ]
    },

    # 7. banking_problems - Post 1
    {
        "category": "banking_problems",
        "title": "Top 10 Common UPI Failures, NPCI Error Codes & Immediate Resolution Hacks",
        "intro_p1": "Unified Payments Interface (UPI) handles billions of transactions monthly in India, but network congestion and bank server timeouts cause occasional transaction failures.",
        "intro_p2": "Resolving UPI errors requires understanding NPCI error codes, bank server status checks, UPI Lite offline wallets, and Banking Ombudsman escalation paths.",
        "items": [
            ("NPCI Error Code 'U16' or 'RM': Bank Server Down", "Cause: Issuer Bank Core System Timeout | Action: Switch Payment Method | Auto-TAT: 24 Hours", "Occurs when issuing bank's core banking server (CBS) fails to respond.", "System auto-reverses debited amount within 24 hours.", "Use UPI Lite or alternate bank account for urgent payments.", "Check UPI server status on bank app before retrying."),
            ("NPCI Error Code 'U30' or 'ZM': Daily Transaction Limit Exceeded", "Cause: RBI / Bank Limit Cap | Cap: ₹1 Lakh per Day / 20 Txns | Solution: Use NEFT/IMPS", "NPCI caps daily UPI transactions at ₹1 Lakh (₹5 Lakhs for hospital/education).", "Maximum 20 UPI transactions permitted per 24-hour rolling window.", "Wait 24 hours or switch to netbanking for larger transfers.", "Split large payments across two distinct bank accounts."),
            ("UPI Error 'Payment Pending': Money Debited but Not Credited", "Status: Interbank Reconciliation | TAT: T+1 Working Day | Escalation: BHIM / NPCI", "Money leaves sender bank but remains pending in NPCI settlement queue.", "DO NOT initiate duplicate payment; status resolves to success or failure.", "NPCI guidelines mandate auto-reversal within T+1 days.", "File dispute on BHIM app if pending past 48 hours."),
            ("UPI Error 'Incorrect UPI PIN / Max Attempts Exceeded'", "Cause: Wrong PIN Entered 3 Times | Penalty: 24-Hour Block | Solution: Reset PIN via Debit Card", "Entering wrong UPI PIN 3 consecutive times blocks UPI access for 24 hours.", "Reset PIN instantly using debit card last 6 digits and expiry date.", "Ensure mobile number registered with bank is in primary SIM slot.", "Never share UPI PIN; PIN is entered ONLY to send money, never receive."),
            ("UPI Error 'Receiver Bank Account Inactive / Frozen'", "Cause: Recipient Account Credit Freeze | Action: Request Alternate VPA / QR", "Sender's money auto-reverses because recipient bank rejects credit.", "Recipient must update KYC or clear account lien with home branch.", "Ask merchant for alternative UPI QR code or bank account number.", "Reversal credits sender account within 2 hours."),
            ("UPI Lite Setup & Offline Transaction Resolution", "Cap: ₹500 per Txn / ₹2,000 Wallet | Tech: On-Device Wallet | Advantage: Zero Pin Needed", "UPI Lite processes micro-payments under ₹500 directly from device wallet.", "Does not depend on bank CBS availability; zero payment failures.", "Recharge wallet online using UPI PIN.", "Ideal for daily tea, groceries, and metro ticket buys."),
            ("UPI AutoPay Mandate Bounces & Revocation Hacks", "Category: Recurring Subscriptions | Action: Pause / Revoke on App | Penalty: Autodebit Bounce", "AutoPay mandates fail if linked savings account lacks adequate balance.", "Manage or revoke recurring mandates under UPI Settings on GPay/PhonePe.", "Canceling app subscription does not automatically revoke UPI AutoPay mandate.", "Revoke mandate on UPI app 24 hours prior to debit date."),
            ("UPI Error 'VPA / QR Code Invalid or Expired'", "Cause: Dynamic QR Expiry / Typo | Action: Re-scan Fresh QR Code", "Dynamic QR codes generated by merchants expire after 5-10 minutes.", "Re-scan fresh QR code or manually verify VPA address (e.g. name@upi).", "Prevents sending money to stale or hijacked payment handles.", "Verify merchant display name on app screen before tapping Pay."),
            ("UPI Transaction Failed Due to SIM Swap / Device Change", "Security: Binding Mechanism | Fix: Re-register Device | Prerequisite: SMS Balance", "Changing phone handset or SIM card unbinds registered UPI app.", "UPI app sends outgoing verification SMS to re-bind device.", "Ensure primary SIM slot has active SMS plan.", "Disable VPN services during device re-binding process."),
            ("Escalating Unresolved UPI Debits to RBI Banking Ombudsman", "Portal: CMS RBI (cms.rbi.org.in) | Window: 30 Days Post Complaint | Relief: ₹100/day Compensation", "If bank fails to resolve stuck UPI refund within 30 days, file RBI Ombudsman case.", "Attach UPI transaction reference (RRR) number and bank statements.", "RBI awards statutory ₹100 per day compensation for delayed reversals.", "Submit online complaint via RBI CMS portal for fast resolution.")
        ]
    }
]
