"""
Part 4 of 39 Authentic Indian Top 10 Posts
Categories: can_i_queries, what_happens_if, bureaucracy, banking_problems
"""

PART_4_POSTS = [
    # 4. can_i_queries - Post 1
    {
        "category": "can_i_queries",
        "title": "Top 10 Indian 'Can I...' Legal & Municipal Queries: Driving, Property & Renovation",
        "intro_p1": "Navigating Indian municipal regulations, motor vehicle rules, and residential property laws often leaves citizens asking essential operational questions. From modifying vehicles to installing rooftop solar, clarity on statutory permissions prevents fines.",
        "intro_p2": "Evaluating municipal rules requires consulting state-specific building bylaws, Motor Vehicles Act amendments, RTO circulars, and Resident Welfare Association (RWA) jurisdiction bounds.",
        "items": [
            ("Can I modify my car's exhaust, tires, or wrap in India?", "Legal Status: Strictly Regulated | Authority: RTO / MV Act Section 52 | Penalty: ₹5,000", "Vehicle structural modifications, loud performance exhausts, and dark window tinting are illegal.", "Color wraps require updating vehicle RC book at RTO.", "Slight tire size upsizing within 3% variance is generally permissible.", "Keep original factory parts if selling or passing RTO fitness tests."),
            ("Can I install solar panels on my apartment roof?", "Legal Status: Allowed with Permission | Authority: DISCOM & RWA | Subsidy: PM Surya Ghar", "Rooftop solar installation requires RWA NOC and DISCOM net-metering approval.", "Eligible for government subsidies under PM Surya Ghar Yojana.", "Excess generated power is credited against monthly electricity bills.", "Submit net-metering application to DISCOM before buying panels."),
            ("Can I break internal walls in my apartment during renovation?", "Legal Status: Conditional | Authority: Municipal Corp & Structural Engineer | Rule: No Load-Bearing", "Non-load bearing brick partitions can be removed with RWA notification.", "Demolishing load-bearing columns or beams is a criminal structural offense.", "Violations trigger municipal stop-work notices and heavy penalties.", "Obtain structural engineer certificate before heavy interior demolition."),
            ("Can I run a commercial office or consulting practice from home?", "Legal Status: Allowed for Professionals | Authority: Municipal Bylaws | Limit: 25% area", "Lawyers, CAs, doctors, and tech consultants can operate residential offices.", "Must not exceed 25% of total residential flat floor area.", "Does not require commercial electricity tariff conversion in most states.", "Check RWA rules regarding client footfall and parking limits."),
            ("Can I drive a vehicle registered in another state without transferring RTO?", "Legal Status: Max 12 Months | Authority: Central Motor Vehicles Rules | Option: BH Series", "Can drive out-of-state vehicle up to 12 months before mandatory RTO re-registration.", "BH (Bharat) series registration allows seamless pan-India transfer without tax hassle.", "Exceeding 12 months makes vehicle liable for road tax recovery and impoundment.", "Keep toll gate receipts and transport bills to prove entry date."),
            ("Can I construct an additional floor on my independent house?", "Legal Status: FSI Dependent | Authority: Local Municipal Development Authority | Fee: FAR Charges", "Constructing extra floors depends on approved Floor Area Ratio (FAR) and road width.", "Requires purchasing extra FAR and submitting updated building map.", "Unauthorized construction faces demolition under municipal acts.", "Verify FAR limits with local municipal architect before buying bricks."),
            ("Can I keep pets in a rented apartment if RWA bans them?", "Legal Status: Permitted | Authority: Animal Welfare Board of India (AWBI) & Courts | Rule: RWA Ban Invalid", "RWA circulars banning pets in apartments are legally void per High Court rulings.", "Landlords cannot evict tenants solely for owning pets unless lease specifies explicit terms.", "Pet owners must ensure pets do not create public nuisance in common areas.", "Keep pet vaccinated and carry AWBI guideline copy if confronted."),
            ("Can I cut a tree inside my private property boundary?", "Legal Status: Restricted | Authority: State Forest Dept / Tree Authority | Fine: Up to ₹50,000", "Felling trees even on private land requires prior written permission from Tree Officer.", "Exemptions exist for dead, diseased, or dangerous trees after inspection.", "Illegal tree cutting leads to criminal FIRs and heavy environmental fines.", "Apply online via municipal green portal before trimming large branches."),
            ("Can I rent out my flat on Airbnb / short-stay portals in India?", "Legal Status: Conditional | Authority: State Tourism Dept & RWA | License: Trade / Homestay", "Short-term commercial renting requires state tourism department registration and RWA NOC.", "Residential RWAs can restrict commercial short-stay guest access on security grounds.", "Failure to register leads to commercial tax evasion notices.", "Check local RWA bylaws before listing property on short-stay apps."),
            ("Can I install EV charging points in my allotted basement parking spot?", "Legal Status: Rights Protected | Authority: Ministry of Power Guidelines | Power: Sub-metering", "Housing societies must permit EV charger installation in allotted parking bays.", "Requires dedicated sub-meter connection from state DISCOM.", "RWA cannot arbitrarily deny approval if safety norms are met.", "Use certified IS-17017 compliant EV charger sockets.")
        ]
    },

    # 4. can_i_queries - Post 2
    {
        "category": "can_i_queries",
        "title": "Top 10 Indian 'Can I...' Passport, Visa & OCI Dual-Citizenship Rules Answered",
        "intro_p1": "Navigating Indian passport renewals, Overseas Citizen of India (OCI) cards, visa endorsements, and dual citizenship regulations involves strict compliance with the Ministry of External Affairs (MEA) and Ministry of Home Affairs (MHA).",
        "intro_p2": "Evaluating immigration rules requires verifying Passports Act 1967 guidelines, OCI registration terms, Bureau of Immigration circulars, and foreign jurisdiction rules.",
        "items": [
            ("Can an Indian citizen hold dual citizenship with another country?", "Legal Status: Prohibited | Authority: Constitution of India Article 9 | Requirement: Surrender Indian Passport", "India does not permit dual citizenship under the Citizenship Act 1955.", "Acquiring foreign citizenship automatically terminates Indian citizenship.", "Must surrender Indian passport within 90 days to avoid monetary penalties.", "Apply for Surrender Certificate immediately upon foreign naturalization."),
            ("Can I travel to India on an expired OCI card if I renewed my foreign passport?", "Legal Status: Permitted for specific ages | Authority: MHA OCI Guidelines | Rule: Online Re-issuance", "OCI holders under 20 or over 50 need online updating of foreign passport details.", "Between ages 20 to 50, re-issuance is not required each time passport renews.", "Travel is permitted as long as foreign passport and OCI card are carried.", "Upload new passport copy on MHA OCI portal free of charge before travel."),
            ("Can I renew my Indian passport 1 year before expiry?", "Legal Status: Permitted | Authority: Passport Seva (MEA) | Window: Within 1 year of expiry", "Passport can be renewed up to 1 year prior to expiry date.", "Crucial for international travel as many countries demand 6-month validity.", "Fast-track renewal available via Tatkaal scheme within 1-3 days.", "Book appointment early as summer vacation slots fill fast."),
            ("Can OCI cardholders purchase agricultural land or farmhouses in India?", "Legal Status: Strictly Prohibited | Authority: FEMA / RBI Guidelines | Rule: Residential Only", "OCI cardholders cannot buy agricultural land, plantation property, or farmhouses.", "Permitted to acquire residential and commercial real estate.", "Inheritance of agricultural land acquired before foreign citizenship is allowed.", "Obtain RBI clearance before executing land transactions."),
            ("Can I travel internationally if my name order differs on Passport vs Visa?", "Legal Status: High Risk | Authority: Bureau of Immigration & Airlines | Action: Name Rectification", "Name mismatch between passport and visa/boarding pass leads to denied boarding.", "First name and surname must strictly match official travel documents.", "Single-name passports (no surname) face entry restrictions in UAE and US.", "Add surname in passport via official gazette notification prior to visa application."),
            ("Can a divorced parent apply for a child's Indian passport without spouse consent?", "Legal Status: Permitted with Annexure C | Authority: Passport Seva | Requirement: Sole Custody Order", "Single/divorced parent can apply using Annexure C explaining circumstances.", "Must produce court order granting sole custody or explanation of spouse absence.", "Prevents child passport delays due to matrimonial disputes.", "Attach certified copy of family court custody order."),
            ("Can OCI cardholders work commercially in India?", "Legal Status: Fully Permitted | Authority: Ministry of Home Affairs | Exception: Govt & Political Jobs", "OCI cardholders enjoy parity with NRIs in economic, financial, and educational fields.", "Can work in private companies, practice medicine, law, architecture, and accounting.", "Cannot vote, hold constitutional posts, or work in government offices.", "No separate employment visa or work permit required."),
            ("Can I visit restricted/protected areas in India (Ladakh border, NE) on an OCI?", "Legal Status: Requires PAP / RAP | Authority: MHA & District Magistrate | Rule: Special Permit Needed", "OCI holders require Protected Area Permit (PAP) or Restricted Area Permit (RAP).", "Applies to border regions in Ladakh, Sikkim, Arunachal Pradesh, Nagaland, and Andaman.", "Standard OCI card does not grant automatic access to strategic border zones.", "Apply for PAP through Ministry of Home Affairs or Resident Commissioner offices."),
            ("Can I change my address on Indian passport while living abroad?", "Legal Status: Permitted | Authority: Indian Embassy / VFS Global | Requirement: Proof of Residence", "Can update Indian or foreign address during passport re-issuance at Indian mission.", "Requires utility bill, bank statement, or rental lease as address proof.", "New passport will reflect updated primary address.", "Submit self-attested address proof copies during VFS appointment."),
            ("Can I retain my Indian SIM card while living abroad as an NRI?", "Legal Status: Fully Permitted | Authority: TRAI Guidelines | Requirement: International Roaming / Top-up", "SIM stays active by maintaining minimum recharge and international roaming pack.", "Essential for receiving Indian bank OTPs, income tax updates, and UPI validation.", "Unused SIM cards are deactivated by telecom operators after 90 days of zero usage.", "Recharge with low-cost annual validity pack to keep number alive.")
        ]
    }
]
